/* Runs before workspace scripts; API requests wait for identity, not untrusted local profiles. */
(function(root){'use strict';const original=root.fetch.bind(root);let identity=null,redirecting=false;document.documentElement.style.visibility='hidden';
const go=()=>{if(redirecting)return;redirecting=true;try{localStorage.clear()}catch{}location.replace('/account.html');};
const ready=original('/api/auth/me',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok){go();throw Error('Войдите в свою учётную запись');}if(!d.enabled){document.documentElement.style.visibility='';return null;}identity=d.user;const owner=identity.id+':'+identity.revision;try{if(localStorage.getItem('adib-account-owner')!==owner){localStorage.clear();localStorage.setItem('adib-account-owner',owner);location.reload();return new Promise(()=>{});}}catch{}root.ADIBAccount.user=identity;document.documentElement.style.visibility='';return identity;});ready.catch(()=>{});
root.ADIBAccount={ready,user:null,section:s=>!identity||identity.role==='admin'||identity.rules.sections.includes(s),action:a=>!identity||identity.role==='admin'||identity.rules.actions.includes(a),open:()=>location.href='/account.html'};
root.fetch=async(input,options)=>{const href=typeof input==='string'?input:input.url;let u;try{u=new URL(href,location.href)}catch{return original(input,options)}if(u.origin===location.origin&&u.pathname.startsWith('/api/')&&!u.pathname.startsWith('/api/auth/')){await ready;const r=await original(input,options);if(r.status===401)go();return r;}return original(input,options);};
function apply(){if(!identity)return;const allowed=root.ADIBAccount.section;for(const b of document.querySelectorAll('[data-home-nav]')){const s=b.dataset.homeNav==='tasks'?'personal':b.dataset.homeNav;b.hidden=!allowed(s);b.style.display=allowed(s)?'':'none';}for(const b of document.querySelectorAll('#adibPersistentSide button,.adib-home-tools button')){const text=b.textContent.trim();const section=text==='Матрица Эйзенхауэра'?'matrix':text==='Канбан'||text==='Холст моих задач'?'personal':text==='Виджеты'?'widgets':text==='Настройки'?'settings':null;if(section)b.style.display=allowed(section)?'':'none';}for(const b of document.querySelectorAll('#deleteTask,#personalEditorDelete,[data-task-delete]'))b.style.display=root.ADIBAccount.action('delete')?'':'none';for(const b of document.querySelectorAll('.adib-home-check'))b.disabled=!root.ADIBAccount.action('status');for(const b of document.querySelectorAll('.adib-home-add'))b.style.display=root.ADIBAccount.action('create')?'':'none';const profile=document.getElementById('currentUser');if(profile){profile.disabled=true;profile.title=identity.name;}if(!document.getElementById('adibAccountButton')&&document.body){const b=document.createElement('button');b.id='adibAccountButton';b.textContent=identity.name+' · Профиль';b.style.cssText='position:fixed;bottom:12px;left:12px;z-index:2000;max-width:210px;padding:8px;border-radius:8px;border:1px solid #bccbea;background:var(--surface,#fff);color:inherit';b.onclick=root.ADIBAccount.open;document.body.append(b);}if(typeof currentUser==='object'&&currentUser.name!==identity.name){currentUser={id:identity.id,name:identity.name};}}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;apply()},80)});const init=()=>{observer.observe(document.body,{childList:true,subtree:true});ready.then(apply).catch(()=>{});};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
// Existing streams carry revision notices only. Revalidate periodically to revoke stale views.
setInterval(async()=>{if(!identity)return;try{const r=await original('/api/auth/me',{cache:'no-store'});if(!r.ok){go();return;}const d=await r.json();if(d.user.revision!==identity.revision)go();else document.documentElement.style.visibility='';}catch{document.documentElement.style.visibility='hidden';}},30000);
})(window);
