'use strict';
// One persistent server is the authority. No client-supplied author/role is trusted.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {promisify}=require('node:util');const scrypt=promisify(crypto.scrypt);
const SECTIONS=['personal','calendar','day','matrix','equipment','chat','widgets','settings'];
const ACTIONS=['create','edit','status','delete','comment','timer'];
const fail=(message,statusCode=403)=>Object.assign(Error(message),{statusCode,code:statusCode===401?'LOGIN_REQUIRED':'ACCESS_DENIED'});
const digest=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const key=s=>String(s||'').replace(/-/g,'').toLowerCase();
function rules(v={}){return {sections:SECTIONS.filter(x=>(v.sections||[]).includes(x)),actions:ACTIONS.filter(x=>(v.actions||[]).includes(x)),containers:v.containers==='*'?'*':[...new Set((Array.isArray(v.containers)?v.containers:[]).map(key))].slice(0,500),plans:v.plans==='*'?'*':[...new Set((Array.isArray(v.plans)?v.plans:[]).map(key))].slice(0,500),assignedOnly:v.assignedOnly===true,assignee:String(v.assignee||'').trim().slice(0,120)};}
function defaults(role){return rules(role==='manager'?{sections:SECTIONS,actions:['create','edit','status','comment','timer'],containers:'*',plans:'*'}:{sections:['personal','calendar','chat'],actions:['status','comment','timer'],containers:[],plans:[],assignedOnly:true});}
function name(v){const s=String(v||'').trim();if(!s||s.length>100||/[\[\]\r\n\x00-\x1f]/.test(s))throw fail('Укажите имя без скобок и управляющих символов',400);return s;}
function login(v){const s=String(v||'').trim().toLowerCase();if(!/^[a-z0-9_.@+-]{3,120}$/.test(s))throw fail('Логин: 3–120 латинских букв, цифр или символов _.@+-',400);return s;}
async function password(v){if(typeof v!=='string'||v.length<12||v.length>256)throw fail('Пароль должен содержать от 12 до 256 символов',400);const salt=crypto.randomBytes(16).toString('hex');return salt+':'+(await scrypt(v,salt,64)).toString('hex');}
async function matches(v,stored){const [salt,hash]=String(stored||'').split(':');const derived=await scrypt(String(v||'').slice(0,256),salt||'invalid-salt',64);return !!hash&&crypto.timingSafeEqual(derived,Buffer.from(hash,'hex'));}
class Accounts {
 constructor({file,enabled=true,adminLogin='',adminPassword='',adminName='Ilqar Mamedov',now=()=>Date.now()}={}){Object.assign(this,{file,enabled,adminLogin,adminPassword,adminName,now});this.state={version:1,users:[],invites:[],sessions:[]};this.attempts=new Map();this.streams=new Set();if(file&&fs.existsSync(file)){this.state=JSON.parse(fs.readFileSync(file,'utf8'));if(this.state.version!==1)throw Error('Неподдерживаемое хранилище аккаунтов');if(this.state.users.length)this.enabled=true;}this.ready=this.initialize();}
 async initialize(){if(this.enabled&&!this.state.users.length&&this.adminPassword){this.state.users.push({id:crypto.randomUUID(),login:login(this.adminLogin||'ilqar'),name:name(this.adminName),password:await password(this.adminPassword),role:'admin',disabled:false,revision:1,rules:defaults('manager')});this.save();}this.adminPassword='';}
 save(){if(!this.file)return;fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(this.state),{mode:0o600});fs.renameSync(tmp,this.file);}
 public(u){return {id:u.id,login:u.login,name:u.name,role:u.role,disabled:!!u.disabled,revision:u.revision,rules:u.rules};}
 token(req){const bearer=String(req.headers.authorization||'').match(/^Bearer ([A-Za-z0-9_-]{43})$/);if(bearer)return bearer[1];const cookie=String(req.headers.cookie||'').match(/(?:^|;\s*)adib_session=([A-Za-z0-9_-]{43})(?:;|$)/);return cookie?.[1]||'';}
 user(req){if(!this.enabled)return null;const s=this.state.sessions.find(s=>s.hash===digest(this.token(req))&&s.expires>this.now());const u=s&&this.state.users.find(u=>u.id===s.userId&&!u.disabled);if(!u)throw fail('Войдите в свою учётную запись',401);return u;}
 session(u){this.state.sessions=this.state.sessions.filter(s=>s.expires>this.now());if(this.state.sessions.length>=5000)throw fail('Слишком много активных сессий',429);const token=crypto.randomBytes(32).toString('base64url');this.state.sessions.push({hash:digest(token),userId:u.id,expires:this.now()+30*86400000});this.save();return {ok:true,token,user:this.public(u)};}
 limit(req){const addr=req.socket?.remoteAddress||'local',now=this.now();if(this.attempts.size>10000)for(const [k,v]of this.attempts)if(v.at<now-900000)this.attempts.delete(k);const v=this.attempts.get(addr)||{at:now,n:0};if(now-v.at>900000){v.at=now;v.n=0;}this.attempts.set(addr,v);if(++v.n>30)throw fail('Слишком много попыток. Повторите через 15 минут.',429);}
 requireAdmin(u){if(u?.role!=='admin')throw fail('Только администратор');}
 async route(req,p,b={}){await this.ready;if(!this.enabled)return {ok:true,enabled:false};
 if(p==='/api/auth/status')return {ok:true,enabled:true,setupRequired:!this.state.users.length};
 if(p==='/api/auth/login'){this.limit(req);const l=login(b.login),u=this.state.users.find(u=>u.login===l);const originalHash=u?.password;const valid=await matches(b.password,originalHash);if(!u||u.disabled||!valid||u.password!==originalHash)throw fail('Неверный логин или пароль',401);return this.session(u);}
 if(p==='/api/auth/accept'){this.limit(req);const invite=this.state.invites.find(i=>i.hash===digest(b.invite)&&!i.used&&i.expires>this.now());if(!invite)throw fail('Приглашение недействительно или истекло',400);const l=login(b.login);if(this.state.users.some(u=>u.login===l))throw fail('Логин уже используется',409);const hash=await password(b.password);if(invite.used||invite.expires<=this.now()||!this.state.invites.includes(invite))throw fail('Приглашение использовано, отозвано или истекло',409);invite.used=true;const u={id:crypto.randomUUID(),login:l,name:invite.name,password:hash,role:invite.role,disabled:false,revision:1,rules:invite.rules};this.state.users.push(u);this.save();return this.session(u);}
 const u=this.user(req);
 if(p==='/api/auth/me')return {ok:true,enabled:true,user:this.public(u)};
 if(p==='/api/auth/logout'){const hash=digest(this.token(req));this.state.sessions=this.state.sessions.filter(s=>s.hash!==hash);this.save();this.closeStreams(u.id);return {ok:true};}
 if(p==='/api/auth/password'){if(!await matches(b.currentPassword,u.password))throw fail('Неверный текущий пароль',401);u.password=await password(b.password);u.revision++;this.state.sessions=this.state.sessions.filter(s=>s.userId!==u.id);this.save();this.closeStreams(u.id);return this.session(u);}
 this.requireAdmin(u);
 if(p==='/api/admin/users'){if(req.method==='GET')return {ok:true,users:this.state.users.map(u=>this.public(u)),invites:this.state.invites.filter(i=>!i.used&&i.expires>this.now()).map(({hash,...i})=>i)};
 const original=this.state.users.find(x=>x.id===b.id);const target=original&&structuredClone(original);if(!target)throw fail('Пользователь не найден',404);if(target.role==='admin'&&((b.role&&b.role!=='admin')||b.disabled===true)&&!this.state.users.some(x=>x.id!==target.id&&x.role==='admin'&&!x.disabled))throw fail('Нельзя отключить последнего администратора',409);
 if(b.name!==undefined)target.name=name(b.name);if(b.role!==undefined){if(!['admin','manager','employee'].includes(b.role))throw fail('Некорректная роль',400);target.role=b.role;}if(b.rules!==undefined)target.rules=rules(b.rules);if(b.disabled!==undefined)target.disabled=b.disabled===true;target.revision++;Object.assign(original,target);this.state.sessions=this.state.sessions.filter(s=>s.userId!==target.id);this.save();this.closeStreams(target.id);return {ok:true,user:this.public(target)};}
 if(p==='/api/admin/invites'){if(req.method==='DELETE'){this.state.invites=this.state.invites.filter(i=>i.id!==b.id);this.save();return {ok:true};}if(!['manager','employee'].includes(b.role||'employee'))throw fail('Приглашения администратора запрещены',400);const token=crypto.randomBytes(32).toString('base64url');const i={id:crypto.randomUUID(),hash:digest(token),name:name(b.name),role:b.role||'employee',rules:rules(b.rules||defaults(b.role)),expires:this.now()+7*86400000,used:false};this.state.invites=this.state.invites.filter(i=>!i.used&&i.expires>this.now());if(this.state.invites.length>=1000)throw fail('Лимит приглашений',429);this.state.invites.push(i);this.save();return {ok:true,invite:token,expires:i.expires,id:i.id};}
 throw fail('Неизвестный маршрут аккаунтов',404);
 }
 closeStreams(id){for(const s of [...this.streams])if(s.id===id){s.response.write('event: access-changed\ndata: {}\n\n');s.response.end();this.streams.delete(s);}}
 track(req,res,u){if(!u)return;const s={id:u.id,response:res};this.streams.add(s);const timer=setInterval(()=>{try{this.user(req);}catch{res.end();}},30000);timer.unref();res.on('close',()=>{clearInterval(timer);this.streams.delete(s);});}
 section(u,s){return !this.enabled||u?.role==='admin'||u?.rules.sections.includes(s);}
 action(u,a){return !this.enabled||u?.role==='admin'||u?.rules.actions.includes(a);}
 task(u,t,kind='personal'){if(!this.enabled||u?.role==='admin')return true;if(!t)return false;const r=u.rules;if(kind==='personal'){if(!['personal','calendar','day','matrix'].some(s=>this.section(u,s)))return false;if(r.containers!=='*'&&!r.containers.includes(key(t.containerId)))return false;}else{if(!this.section(u,'equipment'))return false;if(r.plans!=='*'&&!r.plans.includes(key(t.planId)))return false;}if(!r.assignedOnly)return true;const a=r.assignee;if(!a)return false;return kind==='personal'?(t.assignees||[]).includes(a):(t.assigneeId===a||t.assigneeName===a||(t.tapsirildi||[]).includes(a));}
 filter(u,scope,data){if(!this.enabled||u?.role==='admin')return data;const d=structuredClone(data),allow=(t,k)=>this.task(u,t,k);delete d.database;delete d.containersDatabase;delete d.sync;delete d.cache;delete d.etag;
 if(scope==='personal'){d.tasks=(d.tasks||[]).filter(t=>allow(t,'personal'));d.pomodoroTasks=(d.pomodoroTasks||[]).filter(t=>allow(t,'personal'));const ids=new Set([...d.tasks,...d.pomodoroTasks].map(t=>key(t.id)));for(const t of [...d.tasks,...d.pomodoroTasks]){if(t.parentId&&!ids.has(key(t.parentId)))t.parentId='';t.childIds=(t.childIds||[]).filter(id=>ids.has(key(id)));}d.containers=(d.containers||[]).filter(c=>['personal','calendar','day','matrix'].some(s=>this.section(u,s))&&(u.rules.containers==='*'||u.rules.containers.includes(key(c.id))));const cs=new Set(d.containers.map(c=>key(c.id)));for(const c of d.containers)if(!cs.has(key(c.parentId)))c.parentId=null;}
 if(scope==='equipment'){d.plans=(d.plans||[]).filter(p=>this.section(u,'equipment')&&(u.rules.plans==='*'||u.rules.plans.includes(key(p.id))));const plans=new Set(d.plans.map(p=>key(p.id)));for(const p of d.plans)if(!plans.has(key(p.parentId)))p.parentId=null;d.equipment=(d.equipment||[]).filter(e=>plans.has(key(e.planId)));const machines=new Map(d.equipment.map(e=>[key(e.id),e.planId]));const normalize=t=>({...t,planId:t.planId||machines.get(key(t.machineId))||''});for(const x of [...d.plans,...d.equipment]){x.tasks=(x.tasks||[]).map(normalize).filter(t=>allow(t,'equipment'));delete x.taskCounts;delete x.counts;}d.pomodoroTasks=(d.pomodoroTasks||[]).map(normalize).filter(t=>allow(t,'equipment'));const visible=new Set(d.pomodoroTasks.map(t=>key(t.id)));for(const t of [...d.pomodoroTasks,...d.plans.flatMap(p=>p.tasks||[]),...d.equipment.flatMap(e=>e.tasks||[])]){if(!visible.has(key(t.parentId)))t.parentId='';t.machineIds=(t.machineIds||[]).filter(id=>machines.has(key(id)));}}
 return d;
 }
}
module.exports={Accounts,SECTIONS,ACTIONS,rules,defaults,key,fail};
