(function(root){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
let connectionScope=root.ADIBDesktop?null:location.origin;const ready=root.ADIBDesktop?root.ADIBDesktop.getSettings().then(s=>{connectionScope=s.mode==='notion'?'notion:'+String(s.direct?.syncDataSourceId||''):String(s.serverUrl||location.origin)}):Promise.resolve();const scope=()=>{if(connectionScope===null)throw Error('Bağlantı parametrləri gözlənilir');return connectionScope};
const storage=()=> 'adib-autosave-v1:'+scope();
const bindings=new Map(),owners=new WeakMap(),running=new Set();let retry;
function read(){try{return JSON.parse(localStorage.getItem(storage())||'{}')}catch{return {}}}
function write(q){localStorage.setItem(storage(),JSON.stringify(q))}
function notify(key,text,error=false){const b=bindings.get(key);if(b){b.status.textContent=text;b.status.classList.toggle('error',error);b.resolve.hidden=!error}}
async function sendRecord(key){await ready;if(running.has(key))return;const record=read()[key];if(!record)return;const owner=bindings.get(key);if(record.fresh&&(!owner?.active||!owner.form.isConnected)){record.blocked=true;record.suspended=true;record.error=record.error||'Köhnə qaralama gözləmədədir. Yeni tapşırıqlar yalnız “Yarat” düyməsi ilə yaradılır.';const q=read();q[key]=record;write(q);notify(key,record.error,true);return}if(record.fresh&&owner?.active&&!owner.createRequested){notify(key,'Qaralama cihazda saxlandı · “Yarat” üzərinə klikləyin');return}if(record.blocked){notify(key,record.error||'Saxla yoxlaması tələb olunur',true);return}if(navigator.onLine===false){notify(key,'Cihazda saxlandı · şəbəkəni gözləyir');return}running.add(key);notify(key,'Qənaət…');try{
 const sent=copy(record.body),method=record.fresh?'POST':'PATCH';
 if(record.fresh){record.blocked=true;record.error='Yaradılma yoxlanışı: cavab alınmadı. Barışana qədər yenidən yaratmayın.';const q=read();q[key]=record;write(q)}
 const b=bindings.get(key);let result;if(b)result=await b.options.send(method,sent);else{const response=await fetch(record.endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(sent)});result=await response.json();if(!response.ok)throw Object.assign(Error(result.error||'Saxlama xətası'),{code:result.code})}
 const acknowledgedId=String(result?.id||result?.task?.id||sent.id||'');if(!result?.ok&&!acknowledgedId)throw Error('Yadda saxlama təsdiqi yoxdur');if(record.fresh&&!acknowledgedId)throw Error('Server etiraf etmədi ID . Yenidən yaratma bloklanır.');const id=acknowledgedId;const q=read(),latest=q[key];
 const remainder={id,sourceKey:sent.sourceKey,autosaveBase:{}};for(const [field,value]of Object.entries(latest?.body||{})){if(!['id','autosaveBase','autosaveOperationId','sourceKey'].includes(field)&&!same(value,sent[field])){remainder[field]=value;if(sent[field]!==undefined)remainder.autosaveBase[field]=sent[field];else if(latest.body.autosaveBase?.[field]!==undefined)remainder.autosaveBase[field]=latest.body.autosaveBase[field]}}
 if(Object.keys(remainder).some(k=>!['id','sourceKey','autosaveBase'].includes(k))){q[key]={endpoint:record.endpoint,body:remainder,fresh:false}}else delete q[key];write(q);
 if(b){b.id=id;b.fresh=false;if(b.active){const save=b.editor.querySelector(b.options.saveButton);if(save)save.textContent='İndi saxla'}for(const [field,value]of Object.entries(sent))if(!['id','autosaveBase','autosaveOperationId'].includes(field)){b.base[field]=copy(value);let current;try{current=b.options.collect()}catch{}if(current&&same(current[field],value))b.uiBase[field]=copy(value)}if(b.active&&b.form.isConnected){b.options.apply(sent,{...result,id},record.fresh);b.editor.dispatchEvent(new Event('adib-autosaved',{bubbles:true}))}}
 notify(key,q[key]?'Saxlandı · aşağıdakı dəyişikliklərin təqdim edilməsi':'Bütün dəyişikliklər yadda saxlanıldı');
 }catch(e){const q=read();if(q[key]){q[key].error=e.message;if(e.code==='AUTOSAVE_CONFLICT'||e.code==='TASK_CREATE_PARTIAL')q[key].blocked=true;write(q)}notify(key,(record.fresh?'Yaradılma üçün yoxlama tələb olunur: ':'Cihaz xətası yadda saxlandı: ')+e.message,true)}finally{running.delete(key);const q=read();if(q[key]&&!q[key].blocked){clearTimeout(retry);retry=setTimeout(()=>sendRecord(key),5000)}}}
function dispose(editor){owners.get(editor)?.dispose()}
function bind(editor,options){dispose(editor);const key=options.id?options.endpoint+':'+options.id:options.endpoint+':draft:'+crypto.randomUUID();const status=document.createElement('div');status.className='adib-autosave-status';status.setAttribute('role','status');status.textContent=options.fresh?'Qaralama. Tapşırıq əlavə etmək üçün “Yarat“ düyməsini basın':'Dəyişikliklər avtomatik olaraq saxlanılır';(editor.querySelector('.editor-actions')||editor).append(status);
 let initial;try{initial=options.collect()}catch{initial={}}const resolve=document.createElement('button');resolve.type='button';resolve.textContent='Təkrar edin / yoxlayın';resolve.hidden=true;status.after(resolve);const b={editor,form:editor.querySelector('.task-editor')||editor,active:true,createRequested:false,options,status,resolve,base:copy(initial),uiBase:copy(initial),id:options.id,fresh:options.fresh,dirty:false,timer:null};bindings.set(key,b);owners.set(editor,b);resolve.onclick=()=>{const q=read(),row=q[key];if(!row)return;if(row.fresh&&row.blocked){root.alert('Yaradılma cavabı məlum deyil. Siyahını yeniləyin və tapşırığı yoxlayın Notion. Avtomatik yenidən yaratma bloklanıb.');return}if(row.blocked&&!root.confirm('Cari dəyərləri yoxlayın Notion. Yerli dəyişikliklərinizi onların üzərinə tətbiq edin?'))return;row.blocked=false;row.body.autosaveBase={};write(q);sendRecord(key)};
 function store(){if(!b.active||!b.form.isConnected)return;if(!b.dirty)return;let current;try{current=options.collect()}catch(e){status.textContent=e.message;return}const patch={id:b.id};if(current.sourceKey!==undefined)patch.sourceKey=current.sourceKey;const expected={};for(const [field,value]of Object.entries(current)){if(!['id','sourceKey'].includes(field)&&(b.fresh||!same(value,b.uiBase[field]))){patch[field]=value;if(b.base[field]!==undefined)expected[field]=b.base[field]}}
 if(Object.keys(patch).every(k=>['id','sourceKey'].includes(k)))return;
 if(b.fresh)patch.autosaveOperationId=key.split(':draft:')[1];else patch.autosaveBase=expected;
 if(connectionScope===null){ready.then(()=>{store();sendRecord(key)});return}try{const q=read();const previous=q[key];q[key]={endpoint:options.endpoint,body:{...previous?.body,...patch,autosaveBase:{...previous?.body?.autosaveBase,...patch.autosaveBase}},fresh:b.fresh,blocked:previous?.blocked||false,error:previous?.error};write(q);status.textContent=b.fresh?'Qaralama cihazda saxlandı · “Yarat” üzərinə klikləyin':'Cihazda saxlandı · göndərilməsini gözləyir';editor.dispatchEvent(new Event('adib-autostored',{bubbles:true}));queueMicrotask(()=>editor.dispatchEvent(new Event('adib-autostored',{bubbles:true})))}catch{status.textContent='Lokal olaraq yadda saxlamaq alınmadı. Tətbiqi bağlamayın.';return}return patch;
 }
 function changed(e){if(!b.active||!b.form.isConnected)return;if(!e.target.closest(options.selectors)||e.target.closest('.comments-section,[data-task-pane="chat"]'))return;b.dirty=true;store();clearTimeout(b.timer);if(b.fresh)return;b.timer=setTimeout(()=>sendRecord(key),e.type==='change'&&e.target.matches('select,input[type=checkbox]')?50:1500)}
 editor.addEventListener('input',changed);editor.addEventListener('change',changed);
 const button=editor.querySelector(options.saveButton);if(button){button.textContent=options.fresh?'Yaradın':'İndi saxla';button.onclick=()=>{if(!b.active)return;b.createRequested=true;b.dirty=true;if(store())sendRecord(key)}}
 if(connectionScope!==null&&read()[key]){status.textContent='Cihazda gözlənilən dəyişikliklər var';sendRecord(key)}
 b.dispose=()=>{if(!b.active)return;b.active=false;clearTimeout(b.timer);editor.removeEventListener('input',changed);editor.removeEventListener('change',changed);if(owners.get(editor)===b)owners.delete(editor);if(bindings.get(key)===b)bindings.delete(key);const q=read(),row=q[key];if(row?.fresh&&!running.has(key)){row.blocked=true;row.suspended=true;row.error='Forma bağlandıqdan sonra qaralama dayandırıldı; yenidən yaradılması bloklanır.';write(q)}};return {flush:()=>{store();return sendRecord(key)},dispose:b.dispose};
}
root.addEventListener('online',()=>Object.keys(read()).forEach(sendRecord));root.addEventListener('beforeunload',()=>{for(const b of bindings.values())if(b.dirty)b.editor.dispatchEvent(new Event('change',{bubbles:true}))});
setTimeout(()=>ready.then(()=>Object.keys(read()).forEach(sendRecord)),3000);new MutationObserver(()=>{for(const b of bindings.values())if(!b.form.isConnected)b.dispose()}).observe(document.documentElement,{childList:true,subtree:true});root.ADIBAutosave={bind,dispose,read,sendRecord};
})(window);
