(function(root){'use strict';const T=root.ADIBCalendarTime,HOUR=80;let host,grid,side,heading,clockBadge,feedback,view='month',anchor=root.ADIBClock.date(),autoAnchor=true,query='',container='',gesture=null,lastView='',rangeSupported=false,needsRender=false,nowTimer=null,lastOpened=null,suppressClickUntil=0;const busy=new Set(),pending=new Map();
const F=root.ADIBCalendarFilters,savedCalendar=F.clean(root.ADIBFilters.read('calendar',F.defaults));let advancedFilters=F.clean(savedCalendar);container=savedCalendar.container;query=savedCalendar.query;view=['month','week','day'].includes(savedCalendar.view)?savedCalendar.view:'month';function rememberCalendarFilters(){root.ADIBFilters.write('calendar',{...advancedFilters,container,query,view});}
const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};const button=(label,fn)=>{const b=el('button','',label);b.type='button';b.onclick=fn;return b;};
let filterControl=null,filterDialog=null;
function currentFilters(){return {...advancedFilters,container,query,view};}
function updateFilterControl(){if(!filterControl)return;const count=F.count(currentFilters());filterControl.textContent=count?'Фильтр · '+count:'Фильтр';filterControl.classList.toggle('has-filters',count>0);filterControl.setAttribute('aria-label',count?'Фильтр календаря: '+count+' активных':'Фильтр календаря');filterControl.setAttribute('aria-expanded',String(!!filterDialog));}
function openCalendarFilter(){if(filterDialog){filterDialog.focus();return;}cancelGesture();const draft=F.clean(currentFilters()),d=el('dialog','calendar-filter-dialog'),form=el('form','calendar-filter-form'),head=el('header','calendar-filter-head'),title=el('h2','','Фильтры календаря');title.id='calendarFilterTitle';d.setAttribute('aria-labelledby',title.id);head.append(title,button('×',()=>d.close()));head.lastChild.setAttribute('aria-label','Закрыть без применения');form.append(head,el('p','calendar-filter-hint','Условия применяются вместе. Последний применённый фильтр сохраняется.'));const fields=el('div','calendar-filter-fields'),controls=new Map(),snapshot=root.ADIBHomeBridge.snapshot();
function field(key,label,items){const wrap=el('label','calendar-filter-field'),select=el('select');select.name=key;select.dataset.calendarFilter=key;wrap.append(el('span','',label));for(const [value,label]of items){const option=el('option','',label);option.value=value;option.selected=value===draft[key];select.append(option);}select.value=draft[key];wrap.append(select);fields.append(wrap);controls.set(key,select);select.onchange=()=>{draft[key]=select.value;preview();};return select;}
const scopes=[['','Все контейнеры'],...snapshot.containers.map(c=>[String(c.id),c.name||'Контейнер'])];if(draft.container&&!scopes.some(([key])=>key===draft.container))scopes.push([draft.container,'Сохранённый контейнер']);field('container','Контейнер',scopes);field('completion','Состояние',[['all','Все задачи'],['open','Незавершённые'],['done','Выполненные за последние 7 дней']]);
for(const key of ['status','priority','category','tag','assignee']){const all={status:'Все статусы',priority:'Все приоритеты',category:'Все категории',tag:'Все теги',assignee:'Все ответственные'},none={status:'Без статуса',priority:'Без приоритета',category:'Без категории',tag:'Без тегов',assignee:'Не назначен'};field(key,F.names[key],[['',all[key]],[F.NONE,none[key]],...F.options(key,snapshot.tasks,draft[key]).map(value=>[value,key==='status'?F.labels[value]||value:value])]);}
const queryLabel=el('label','calendar-filter-field'),search=el('input');search.type='search';search.name='query';search.dataset.calendarFilter='query';search.value=draft.query;search.placeholder='Название задачи';search.oninput=()=>{draft.query=search.value;preview();};queryLabel.append(el('span','','Поиск'),search);controls.set('query',search);fields.append(queryLabel);form.append(fields);const summary=el('p','calendar-filter-preview');summary.setAttribute('role','status');summary.setAttribute('aria-live','polite');form.append(summary);const footer=el('footer','calendar-filter-footer');footer.append(button('Сбросить',()=>{Object.assign(draft,F.defaults,{view});for(const [key,control]of controls)control.value=draft[key];preview();}),button('Отмена',()=>d.close()));const apply=el('button','calendar-filter-apply','Применить');apply.type='submit';footer.append(apply);form.append(footer);form.onsubmit=event=>{event.preventDefault();for(const [key,control]of controls)draft[key]=control.value;advancedFilters=F.clean(draft);container=draft.container;query=draft.query;rememberCalendarFilters();const scope=host?.querySelector('[aria-label="Контейнер календаря"]'),input=host?.querySelector('[aria-label="Поиск задач календаря"]');if(scope){if(container&&![...scope.options].some(o=>o.value===container)){const option=el('option','','Сохранённый контейнер');option.value=container;scope.append(option);}scope.value=container;}if(input)input.value=query;d.close();render();};function preview(){const tasks=root.ADIBHomeBridge.snapshot().tasks;summary.textContent='По загруженным задачам: '+tasks.filter(t=>!t.parentId&&root.ADIBTaskHistory.visible(t)&&F.matches(t,draft,root.ADIBTaskHistory.done)).length+'. Фильтр действует в месяце, неделе, дне и списке «Без даты».';}
d.append(form);document.body.append(d);filterDialog=d;d.addEventListener('close',()=>{d.remove();if(filterDialog===d)filterDialog=null;updateFilterControl();});d.showModal();preview();updateFilterControl();}

function data(){const s=root.ADIBHomeBridge.snapshot();return {...s,tasks:s.tasks.map(t=>pending.has(String(t.id))?{...t,...pending.get(String(t.id)).desired}:t).filter(t=>!t.parentId&&root.ADIBTaskHistory.visible(t)&&F.matches(t,currentFilters(),root.ADIBTaskHistory.done))};}
function message(text,error=false){if(feedback){feedback.textContent=text+' · календарь 1.1.50';feedback.classList.toggle('error',error);}}
function cancelGesture(){if(!gesture)return;gesture.node?.classList.remove('calendar-dragging');gesture.ghost?.remove();gesture=null;render();}
function close(){if(filterDialog){filterDialog.close();filterDialog.remove();filterDialog=null;}filterControl=null;clearInterval(nowTimer);nowTimer=null;cancelGesture();host?.remove();host=null;lastView='';document.body.classList.remove('adib-calendar-open');}
async function save(id,changes,requireRange=false){id=String(id);const task=data().tasks.find(t=>String(t.id)===id);if(!task)return false;if(requireRange&&!rangeSupported){message('Обновите сервер ADIB: он не подтверждает поддержку интервалов календаря.',true);return false;}
 let state=pending.get(id);if(!state){state={desired:{},version:0,running:false,waiters:[]};pending.set(id,state);}state.desired={...changes};state.version++;busy.add(id);message('Изменение показано · ожидает сохранения в Notion');render();
 const result=new Promise(resolve=>state.waiters.push(resolve));clearTimeout(state.timer);if(!state.running)state.timer=setTimeout(()=>flushCalendar(id,state),180);return result;}
async function flushCalendar(id,state){if(state.running||pending.get(id)!==state)return;state.running=true;try{while(pending.get(id)===state){const version=state.version,changes={...state.desired},task=root.ADIBHomeBridge.snapshot().tasks.find(t=>String(t.id)===id);if(!task)throw Error('Задача не найдена');await root.ADIBHomeBridge.patch(id,{...changes,autosaveBase:{date:task.date||'',dateEnd:task.dateEnd||''}});if(version===state.version){pending.delete(id);busy.delete(id);state.waiters.forEach(r=>r(true));message(pending.size?'Сохраняю остальные изменения…':'Время сохранено');break;}}}catch(e){pending.delete(id);busy.delete(id);state.waiters.forEach(r=>r(false));message('Не удалось сохранить время: '+e.message+'. Показан подтверждённый интервал.',true);}finally{state.running=false;render();}}

function move(id,day){const task=data().tasks.find(t=>String(t.id)===String(id));if(!task)return Promise.resolve(false);const changes=T.moveDay(task,day);return save(id,changes,!!changes.dateEnd);}
function schedule(id,day,minute){const task=data().tasks.find(t=>String(t.id)===String(id));return task?save(id,T.slot(day,minute,T.interval(task).duration),true):Promise.resolve(false);}
function dropzone(node,day,timed=false){node.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-adib-task')){e.preventDefault();node.classList.add('drop-target');}});node.addEventListener('dragleave',()=>node.classList.remove('drop-target'));node.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();node.classList.remove('drop-target');const id=e.dataTransfer.getData('application/x-adib-task');if(!id)return;const minute=Math.max(0,Math.min(1425,Math.round((e.clientY-node.getBoundingClientRect().top)*60/HOUR/T.STEP)*T.STEP));void(timed?schedule(id,day,minute):move(id,day));});}
function openTask(id){
 if(gesture)return;
 // Click, touch, and keyboard all open the existing editor, independently of range support.
 const modal=document.getElementById('taskModal');
 if(lastOpened&&String(lastOpened.id)===String(id)&&performance.now()-lastOpened.at<500&&modal?.classList.contains('open'))return;
 root.ADIBHomeBridge.openTask(id);lastOpened={id,at:performance.now()};
}
function card(task,noDate=false){const row=el('article','adib-calendar-task');row.dataset.calendarTask=task.id;row.draggable=!busy.has(String(task.id));row.classList.toggle('calendar-saving',busy.has(String(task.id)));row.addEventListener('dragstart',e=>{if(busy.has(String(task.id))){e.preventDefault();return;}e.dataTransfer.setData('application/x-adib-task',String(task.id));e.dataTransfer.effectAllowed='move';});const title=button(task.title,()=>openTask(task.id));title.className='calendar-task-title';row.append(title);row.tabIndex=0;row.addEventListener('click',e=>{if(!e.target.closest('button')&&performance.now()>=suppressClickUntil)openTask(task.id);});row.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.target.closest('button')){e.preventDefault();openTask(task.id);}});row.addEventListener('dragend',()=>{suppressClickUntil=performance.now()+500;});const range=T.interval(task);if(!range.allDay)row.append(el('small','',T.time(T.minutes(range.start))+'–'+T.time(T.minutes(range.end))));if(noDate){const today=button('На сегодня →',()=>move(task.id,T.key(root.ADIBClock.date())));today.dataset.dateToday=task.id;row.append(today);}return row;}
function dayKeys(){let start=T.fromParts(anchor.getFullYear(),anchor.getMonth(),1),count=42;if(view==='month')start.setDate(1-(start.getDay()+6)%7);else{start=T.clone(anchor);if(view==='week'){start.setDate(start.getDate()-(start.getDay()+6)%7);count=7;}else count=1;}return Array.from({length:count},(_,n)=>{const d=T.clone(start);d.setDate(start.getDate()+n);return T.key(d);});}
function dayHeader(day,full=false){const d=T.parse(day),head=el('header','calendar-day-head');head.classList.toggle('today',day===T.key(root.ADIBClock.date()));head.append(el('strong','',d.toLocaleDateString('ru',{weekday:'short',day:'numeric',...(full?{month:'long'}:{month:'short'})})));const add=button('+',()=>root.ADIBHomeBridge.newTask({calendar:true,date:day,containerId:container||undefined}));add.setAttribute('aria-label','Добавить задачу на '+day);head.append(add);return head;}
function renderMonth(s,days){for(const label of ['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'])grid.append(el('div','adib-calendar-weekday',label));for(const day of days){const d=T.parse(day),cell=el('section','adib-calendar-cell');cell.dataset.calendarDate=day;cell.classList.toggle('outside',d.getMonth()!==anchor.getMonth());cell.append(dayHeader(day));for(const task of s.tasks.filter(t=>T.parse(t.date)&&T.key(T.parse(t.date))===day))cell.append(card(task));dropzone(cell,day);grid.append(cell);}}
function positionEvent(node,part){node.style.top=(part.start*HOUR/60)+'px';node.style.height=Math.max(24,(part.end-part.start)*HOUR/60)+'px';node.style.left=`calc(${part.lane/part.lanes*100}% + 3px)`;node.style.width=`calc(${100/part.lanes}% - 6px)`;node.classList.toggle('calendar-short',part.end-part.start<30);node.classList.toggle('calendar-medium',part.end-part.start<=30);}
function timedEvent(part){const task=part.task,node=el('article','calendar-time-event');node.draggable=false;node.dataset.calendarTask=task.id;node.dataset.calendarEvent=task.id;node.dataset.calendarDay=part.day;node.tabIndex=0;node.setAttribute('aria-label',task.title+', '+T.time(part.start)+'–'+T.time(part.end));node.title=task.title+' · '+T.time(part.start)+'–'+T.time(part.end);node.classList.toggle('calendar-saving',busy.has(String(task.id)));positionEvent(node,part);node.append(el('strong','calendar-event-title',task.title),el('small','calendar-event-time',view==='week'?T.time(part.start):T.time(part.start)+'–'+T.time(part.end)));const controls=button('⋯',()=>eventMenu(task));controls.className='calendar-event-menu';controls.disabled=false;controls.setAttribute('aria-label','Время и действия задачи '+task.title);node.append(controls);
for(const [kind,visible,label] of [['start',part.first,'Изменить начало задачи'],['end',part.last,'Изменить окончание задачи']])if(visible){const handle=el('div','calendar-resize calendar-resize-'+kind);handle.dataset.calendarResize=kind;handle.setAttribute('aria-hidden','true');handle.title=label;node.append(handle);}
node.addEventListener('click',e=>{if(performance.now()>=suppressClickUntil&&!e.target.closest('button')&&!gesture&&!node.classList.contains('calendar-dragging'))openTask(task.id);});node.addEventListener('pointerdown',e=>beginGesture(e,node,part),true);node.addEventListener('dragstart',e=>e.preventDefault());node.addEventListener('lostpointercapture',e=>{if(gesture?.node===node&&gesture.pointerId===e.pointerId)cancelGesture();});node.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();openTask(task.id);}else if(e.key===' '){e.preventDefault();eventMenu(task);}});return node;}
function renderTime(s,days){const layout=el('div','calendar-time-layout');layout.style.setProperty('--calendar-days',days.length);layout.classList.toggle('calendar-one-day',days.length===1);layout.append(el('div','calendar-time-corner','Время'));for(const day of days)layout.append(dayHeader(day,days.length===1));layout.append(el('div','calendar-allday-label','Весь день'));for(const day of days){const lane=el('section','calendar-allday');lane.dataset.calendarDate=day;for(const task of s.tasks.filter(t=>T.interval(t).allDay&&T.parse(t.date)&&T.key(T.parse(t.date))===day))lane.append(card(task));dropzone(lane,day);layout.append(lane);}
const ruler=el('div','calendar-hour-ruler');for(let h=0;h<24;h++){const label=el('span','calendar-hour-label',T.time(h*60));label.style.top=(h*HOUR)+'px';ruler.append(label);}layout.append(ruler);
for(const day of days){const col=el('section','calendar-time-day');col.dataset.calendarTimeDay=day;col.setAttribute('aria-label','Часовая сетка '+day);col.style.setProperty('--calendar-hour-height',HOUR+'px');dropzone(col,day,true);col.ondblclick=e=>{if(e.target.closest('.calendar-time-event'))return;const minute=Math.max(0,Math.min(1425,Math.round((e.clientY-col.getBoundingClientRect().top)*60/HOUR/T.STEP)*T.STEP));if(!rangeSupported){message('Для задач со временем обновите сервер ADIB.',true);return;}root.ADIBHomeBridge.newTask({calendar:true,...T.slot(day,minute),containerId:container||undefined});};const segments=s.tasks.flatMap(t=>T.segments(t,[day]));for(const part of T.layout(segments))col.append(timedEvent(part));layout.append(col);}grid.append(layout);updateNowLine();}
// Update only the marker: never replace task nodes or interrupt a pointer gesture.
function updateNowLine(){
 if(!host||view==='month')return;
 if(!root.ADIBClock.trusted){grid.querySelectorAll('.calendar-now-line,.calendar-now-label').forEach(n=>n.remove());return;}const now=root.ADIBClock.date(),today=T.key(now),minute=T.minutes(now)+now.getSeconds()/60;
 const columns=[...grid.querySelectorAll('.calendar-time-day')],visible=columns.some(c=>c.dataset.calendarTimeDay===today);
 for(const col of columns){
  let line=col.querySelector('.calendar-now-line');
  if(!visible){line?.remove();continue;}
  if(!line){line=el('div','calendar-now-line');line.setAttribute('aria-hidden','true');col.append(line);}
  line.style.top=(minute*HOUR/60)+'px';line.classList.toggle('calendar-now-today',col.dataset.calendarTimeDay===today);
 }
 const ruler=grid.querySelector('.calendar-hour-ruler');let label=ruler?.querySelector('.calendar-now-label');
 if(!visible){label?.remove();return;}
 if(!label){label=el('span','calendar-now-label');ruler?.append(label);}
 clockBadge.textContent='Сетевое время · '+T.time(T.minutes(now))+' · '+root.ADIBClock.timeZone;label.textContent=T.time(T.minutes(now));label.style.top=(minute*HOUR/60)+'px';label.setAttribute('aria-label','Текущее время '+label.textContent);
}
function render(){if(!host)return;updateFilterControl();if(gesture){needsRender=true;return;}const previousScroll=grid.scrollTop,newView=lastView!==view;clockBadge.textContent=root.ADIBClock.trusted?'Сетевое время · '+root.ADIBClock.date().toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})+' · '+root.ADIBClock.timeZone:'Сетевое время не подтверждено';const s=data(),days=dayKeys();heading.textContent=view==='month'?anchor.toLocaleDateString('ru',{month:'long',year:'numeric'}):view==='day'?anchor.toLocaleDateString('ru',{day:'numeric',month:'long',year:'numeric'}):T.parse(days[0]).toLocaleDateString('ru',{day:'numeric',month:'short'})+' — '+T.parse(days[6]).toLocaleDateString('ru',{day:'numeric',month:'short',year:'numeric'});grid.replaceChildren();side.replaceChildren();grid.dataset.view=view;host.dataset.calendarView=view;view==='month'?renderMonth(s,days):renderTime(s,days);const undated=s.tasks.filter(t=>!t.date);side.append(el('h3','','Без даты · '+undated.length),el('small','',view==='month'?'Перетащите задачу на день':'Перетащите на нужный день и время · новая длительность 30 мин'));dropzone(side,'');for(const task of undated)side.append(card(task,true));if(!undated.length)side.append(el('p','','Все задачи имеют дату'));grid.scrollTop=newView&&view!=='month'?Math.max(0,(T.minutes(root.ADIBClock.date())/60-1)*HOUR):previousScroll;lastView=view;needsRender=false;}
function locate(x,y){return [...grid.querySelectorAll('.calendar-time-day')].find(c=>{const r=c.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=Math.max(r.top,grid.getBoundingClientRect().top)&&y<=Math.min(r.bottom,grid.getBoundingClientRect().bottom);});}
function beginGesture(e,node,part){if(e.button!==0||e.target.closest('button'))return;e.preventDefault();e.stopPropagation();if(gesture)cancelGesture();
const rect=node.getBoundingClientRect(),edge=Math.min(10,rect.height/4),localY=e.clientY-rect.top;
const explicit=e.target.closest('[data-calendar-resize]')?.dataset.calendarResize;
const kind=explicit||(part.first&&localY<=edge?'start':part.last&&localY>=rect.height-edge?'end':'move');
try{node.setPointerCapture(e.pointerId);}catch{}gesture={node,part,kind,pointerId:e.pointerId,x:e.clientX,y:e.clientY,start:T.interval(part.task).start,end:T.interval(part.task).end,duration:T.interval(part.task).duration,offset:(e.clientY-node.getBoundingClientRect().top)*60/HOUR,changed:false,valid:true};}
function gestureMove(e){const g=gesture;if(!g||g.pointerId!==e.pointerId)return;if(Math.abs(e.clientX-g.x)+Math.abs(e.clientY-g.y)<4&&!g.changed)return;e.preventDefault();e.stopImmediatePropagation();g.changed=true;if(!rangeSupported){g.valid=false;message('Перенос времени недоступен: сервер не подтвердил поддержку интервалов. Установите серверную версию 1.1.50 и нажмите «Обновить».',true);return;}g.node.classList.add('calendar-dragging');const col=locate(e.clientX,e.clientY);g.valid=!!col;if(!col){g.ghost?.remove();g.ghost=null;return;}
const r=col.getBoundingClientRect(),day=col.dataset.calendarTimeDay;let minute=Math.max(0,Math.min(1440,Math.round((e.clientY-r.top)*60/HOUR/T.STEP)*T.STEP));let a,b;if(g.kind==='move'){minute=Math.max(0,Math.min(1425,Math.round((minute-g.offset)/T.STEP)*T.STEP));const result=T.slot(day,minute,g.duration);a=T.parse(result.date);b=T.parse(result.dateEnd);}else{const d=T.parse(day);d.setMinutes(minute);if(g.kind==='start'){a=d;b=g.end;if(a>b-T.STEP*60000)a=T.clone(new Date(b.getTime()-T.STEP*60000));}else{a=g.start;b=d;if(b<a.getTime()+T.STEP*60000)b=T.clone(new Date(a.getTime()+T.STEP*60000));}}
if((b-a)/60000>T.MAX){g.valid=false;return;}g.changes={date:a.toISOString(),dateEnd:b.toISOString()};g.ghost?.remove();const ghost=el('div','calendar-event-preview');ghost.style.top=(Math.max(0,T.key(a)===day?T.minutes(a):0)*HOUR/60)+'px';ghost.style.height=Math.max(20,((T.key(b)===day?T.minutes(b):1440)-(T.key(a)===day?T.minutes(a):0))*HOUR/60)+'px';ghost.textContent=T.time(T.minutes(a))+'–'+T.time(T.minutes(b));col.append(ghost);g.ghost=ghost;
const bounds=grid.getBoundingClientRect();if(e.clientY>bounds.bottom-36)grid.scrollTop+=18;else if(e.clientY<bounds.top+70)grid.scrollTop-=18;const visible=grid.getBoundingClientRect();if(e.clientX>visible.right-24)grid.scrollLeft+=18;else if(e.clientX<visible.left+70)grid.scrollLeft-=18;}
function gestureEnd(e){const g=gesture;if(!g||g.pointerId!==e.pointerId)return;gesture=null;if(g.changed)suppressClickUntil=performance.now()+500;e.preventDefault();e.stopImmediatePropagation();try{g.node.releasePointerCapture(e.pointerId);}catch{}g.node.classList.remove('calendar-dragging');g.ghost?.remove();if(g.changed&&g.valid&&g.changes)void save(g.part.task.id,g.changes,true);else{render();if(!g.changed)openTask(g.part.task.id);}}
function eventMenu(task){const ui=root.ADIBTaskCards.dialog('Календарь · '+task.title);ui.dialog.querySelector('h2').textContent='Время задачи';const interval=T.interval(task),local=d=>T.key(d)+'T'+T.time(T.minutes(d)),start=el('input',''),end=el('input','');start.type=end.type='datetime-local';start.value=local(interval.start);end.value=local(interval.end);start.step=end.step=900;for(const [text,input]of [['Начало',start],['Окончание',end]]){const label=el('label','',text);label.append(input);ui.fields.append(label);}const err=el('p','calendar-form-error');err.setAttribute('role','alert');ui.fields.append(err);ui.footer.append(button('Свойства',()=>{ui.close();openTask(task.id);}),button('Без даты',async()=>{if(await move(task.id,''))ui.close();}),button('Сохранить',async e=>{const a=T.parse(start.value),b=T.parse(end.value);if(!a||!b||b-a<T.STEP*60000||b-a>T.MAX*60000){err.textContent='Интервал от 15 минут до 7 дней. Окончание должно быть позже начала.';return;}e.currentTarget.disabled=true;const ok=await save(task.id,{date:a.toISOString(),dateEnd:b.toISOString()},true);if(ok)ui.close();else{e.currentTarget.disabled=false;err.textContent=feedback.textContent;}}));ui.footer.lastChild.classList.add('primary');ui.dialog.showModal();}
async function checkCapabilities(owner=host){
 try{
  const result=await Promise.resolve().then(()=>root.ADIBHomeBridge.calendarCapabilities());
  if(host!==owner)return;const cap=result?.body||result;rangeSupported=cap?.dateRange===true;
  message(rangeSupported?'Перенос: тело карточки · начало/окончание: края · шаг 15 мин · клик: свойства':'Интервалы недоступны. Обновите сервер до 1.1.50 и нажмите «Обновить». Открытие свойств доступно.',!rangeSupported);
 }catch(error){if(host===owner){rangeSupported=false;message('Не удалось проверить интервалы. Свойства открываются по клику; для переноса проверьте сервер и нажмите «Обновить».',true);}}
}
function open(){if(!root.ADIBClock.trusted){void root.ADIBClock.refresh(true);root.ADIBClock.details();return;}if(autoAnchor)anchor=root.ADIBClock.date();root.ADIBHome.leave(()=>{close();host=el('section','adib-calendar');host.id='adibCalendar';host.dataset.calendarVersion='1.1.50';document.body.classList.add('adib-calendar-open');const top=el('header','adib-calendar-bar');top.append(button('‹',()=>{autoAnchor=false;if(view==='month')anchor=T.fromParts(anchor.getFullYear(),anchor.getMonth()-1,1);else anchor.setDate(anchor.getDate()-(view==='week'?7:1));render();}),button('›',()=>{autoAnchor=false;if(view==='month')anchor=T.fromParts(anchor.getFullYear(),anchor.getMonth()+1,1);else anchor.setDate(anchor.getDate()+(view==='week'?7:1));render();}),button('Сегодня',()=>{autoAnchor=true;anchor=root.ADIBClock.date();render();}));heading=el('h2','','');top.append(heading);clockBadge=button('Сетевое время',()=>root.ADIBClock?.details());clockBadge.className='adib-calendar-clock';top.append(clockBadge);const scope=el('select','');scope.setAttribute('aria-label','Контейнер календаря');for(const c of [{id:'',name:'Все задачи'},...root.ADIBHomeBridge.snapshot().containers]){const o=el('option','',c.name);o.value=c.id;o.selected=String(c.id)===container;scope.append(o);}if(container&&![...scope.options].some(o=>o.value===container)){const savedScope=el('option','','Сохранённый контейнер');savedScope.value=container;savedScope.selected=true;scope.append(savedScope);}scope.onchange=()=>{container=scope.value;rememberCalendarFilters();render();};const input=el('input','');input.type='search';input.placeholder='Поиск задач…';input.value=query;input.setAttribute('aria-label','Поиск задач календаря');input.oninput=()=>{query=input.value;rememberCalendarFilters();render();};const mode=el('select','');mode.id='calendarViewMode';for(const [key,label]of [['month','Месяц'],['week','Неделя'],['day','День']]){const o=el('option','',label);o.value=key;o.selected=key===view;mode.append(o);}mode.onchange=()=>{cancelGesture();view=mode.value;rememberCalendarFilters();render();};filterControl=button('Фильтр',openCalendarFilter);filterControl.className='calendar-filter-button';filterControl.id='calendarFilterButton';filterControl.setAttribute('aria-haspopup','dialog');top.append(scope,input,filterControl,mode,button('Обновить',async()=>{await root.ADIBClock.refresh(true);await checkCapabilities(host);try{await root.ADIBHomeBridge.refresh(false);render();}catch(error){message('Обновление не удалось: '+error.message,true);}}),button('×',()=>root.ADIBHome.open()));feedback=el('div','adib-calendar-status','Проверяю поддержку интервалов…');feedback.setAttribute('role','status');grid=el('main','adib-calendar-grid');side=el('aside','adib-calendar-undated');const body=el('div','adib-calendar-body');body.append(grid,side);host.append(top,feedback,body);document.body.append(host);rangeSupported=false;render();nowTimer=setInterval(updateNowLine,15000);void checkCapabilities(host);});}
document.addEventListener('pointermove',gestureMove,{passive:false,capture:true});document.addEventListener('pointerup',gestureEnd,true);document.addEventListener('pointercancel',e=>{if(gesture?.pointerId===e.pointerId)cancelGesture();},true);root.addEventListener('blur',()=>cancelGesture());document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelGesture();else updateNowLine();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&gesture){e.preventDefault();cancelGesture();}});root.addEventListener('adib-home-data',()=>render());root.addEventListener('adib-clock-change',()=>{if(autoAnchor)anchor=root.ADIBClock.date();render();});root.ADIBCalendar={open,close,move,schedule,goto:key=>{autoAnchor=false;anchor=T.parse(key);render();},get visible(){return !!host;}};
})(window);
