const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict'),{test,before,after}=require('node:test'),{createRequire}=require('node:module');
const root=path.resolve(__dirname,'..'),id='11111111-1111-4111-8111-111111111111';let child,base,temp;
before(async()=>{temp=fs.mkdtempSync(path.join(os.tmpdir(),'adib141-'));child=spawn(process.execPath,[root+'/server.js'],{env:{...process.env,PORT:'0',NOTION_TOKEN:'',TASK_MANAGEMENT_FILE:temp+'/management.json',POMODORO_STATE_FILE:temp+'/timer.json',COMPLETION_HISTORY_FILE:temp+'/history.json'},stdio:['ignore','pipe','pipe']});let output='';await new Promise((resolve,reject)=>{child.stdout.on('data',c=>{output+=c;const m=output.match(/http:\/\/localhost:(\d+)/);if(m){base='http://127.0.0.1:'+m[1];resolve()}});child.on('exit',code=>reject(Error('server exit '+code)));setTimeout(()=>reject(Error('start timeout '+output)),10000).unref()})});
after(()=>{child?.kill();if(temp)fs.rmSync(temp,{recursive:true,force:true})});
test('health, capabilities and release metadata are available',async()=>{assert.equal((await fetch(base+'/api/health')).status,200);const r=await(await fetch(base+'/api/calendar-capabilities')).json();assert.equal(r.dateRange,true);assert.equal(r.version,'1.1.43');assert.equal((await(await fetch(base+'/version.json')).json()).version,'1.1.43')});
test('every local script, stylesheet and icon in full shell is served with correct MIME',async()=>{const html=await(await fetch(base+'/')).text();const assets=[...html.matchAll(/<(?:script|link)[^>]+(?:src|href)="([^"]+)"/g)].map(m=>m[1]).filter(n=>!n.startsWith('http')&&!n.startsWith('data:'));for(const n of assets){const r=await fetch(new URL(n,base+'/'));assert.equal(r.status,200,n);const ext=new URL(n,base+'/').pathname.split('.').pop();if(ext==='js')assert.match(r.headers.get('content-type'),/javascript/,n);if(ext==='css')assert.match(r.headers.get('content-type'),/text\/css/,n)}});
test('calendar code is no-store and release-specific links bypass old caches',async()=>{const r=await fetch(base+'/calendar-view.js?v=1.1.43');assert.equal(r.headers.get('cache-control'),'no-store');assert.match(await r.text(),/Click, touch, and keyboard/);assert.match(await(await fetch(base+'/')).text(),/calendar-view\.js\?v=1\.1\.43/)});
test('private config and backend modules are not public',async()=>{for(const p of ['/.env','/data/task-management.json','/server.js','/task-management.js','/image-upload.js'])assert.equal((await fetch(base+p)).status,404,p)});
function engine(){let handler;const files=new Map(),calls=[],native=createRequire(root+'/server.js'),mods={};const fakefs={existsSync:p=>files.has(p),readFileSync:p=>{if(!files.has(p))throw Error('missing fixture');return files.get(p)},writeFileSync:(p,s)=>files.set(p,s),mkdirSync(){},renameSync:(a,b)=>{files.set(b,files.get(a));files.delete(a)}};
function req(n){if(n==='node:http')return{createServer:fn=>{handler=fn;return{listen(){},address(){return{port:0}}}}};if(n==='node:fs')return fakefs;if(n.startsWith('./')){if(!mods[n]){const m={exports:{}};new Function('require','module','exports',fs.readFileSync(path.join(root,n+'.js'),'utf8'))(req,m,m.exports);mods[n]=m.exports}return mods[n]}return native(n)}
const c=vm.createContext({require:req,__dirname:'/fixture',process:{env:{}},console,URL,Buffer,structuredClone,setTimeout,clearTimeout,AbortController,fetch:()=>{throw Error('live network forbidden')}});vm.runInContext(fs.readFileSync(root+'/server.js','utf8'),c);c.stubNotion=async(p,opt={})=>{const body=JSON.parse(opt.body||'{}');calls.push({p,...opt,body});return{id,properties:body.properties||{Tarix:{date:{start:'2026-10-09T09:00:00Z',end:'2026-10-09T10:00:00Z'}}}}};vm.runInContext('notion=stubNotion',c);return{calls,call:(name,...args)=>{c.args=args;return vm.runInContext(name+'(...args)',c)}}}
test('real server PATCH persists both Tarix edges and confirms them',async()=>{const e=engine(),r=await e.call('savePersonalTask',{id,date:'2026-10-09T10:00:00Z',dateEnd:'2026-10-09T11:30:00Z'});assert.deepEqual(e.calls[0].body.properties.Tarix.date,{start:'2026-10-09T10:00:00Z',end:'2026-10-09T11:30:00Z'});assert.equal(r.task.dateEnd,'2026-10-09T11:30:00Z');assert.equal(Object.keys(e.calls[0].body.properties).length,1)});
test('end precedes start: rejected before any Notion write',async()=>{const e=engine();await assert.rejects(e.call('savePersonalTask',{id,date:'2026-10-09T10:00:00Z',dateEnd:'2026-10-09T09:00:00Z'}),x=>x.statusCode===400);assert.equal(e.calls.length,0)});
test('changing start alone preserves duration',async()=>{const e=engine();await e.call('savePersonalTask',{id,date:'2026-10-09T12:00:00Z'});assert.equal(e.calls.at(-1).body.properties.Tarix.date.end,'2026-10-09T13:00:00.000Z')});
test('all-day and removing date supported',async()=>{const e=engine();await e.call('savePersonalTask',{id,date:'2026-10-10',dateEnd:''});assert.equal(e.calls.at(-1).body.properties.Tarix.date.end,null);await e.call('savePersonalTask',{id,date:'',dateEnd:''});assert.equal(e.calls.at(-1).body.properties.Tarix.date,null)});
test('task mapping returns stored dateEnd',()=>{const e=engine(),r=e.call('mapPersonalTask',{id,properties:{Tarix:{date:{start:'2026-10-09T09:00:00Z',end:'2026-10-09T10:00:00Z'}}}});assert.equal(r.dateEnd,'2026-10-09T10:00:00Z')});
