const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const html=fs.readFileSync(__dirname+'/ela-nov-paketleme-dynamic.html','utf8');
const code=html.slice(html.indexOf('function personalDesktopGridContainers('),html.indexOf('function renderPersonalDesktopGrid('));
function env(){const containers=[{id:'root',name:'Root',order:2},{id:'earlier',name:'Earlier',order:1},{id:'child',name:'Nested',parentId:'root'},{id:'deep',name:'Deep',parentId:'child'},{id:'orphan',name:'Orphan',parentId:'deleted',order:3}];const c=vm.createContext({personalLayout:{containers},personalTasksForContainer:id=>id==='root'?[{title:'Needle task'}]:[]});vm.runInContext(code,c);return c}
const ids=xs=>Array.from(xs,x=>x.id);
test('desktop root includes top-level and orphaned containers, excludes nested',()=>{const c=env();assert.deepEqual(ids(c.personalDesktopGridContainers('')),['earlier','root','orphan'])});
test('container view includes only immediate children',()=>{const c=env();assert.deepEqual(ids(c.personalDesktopGridContainers('root')),['child']);assert.deepEqual(ids(c.personalDesktopGridContainers('child')),['deep'])});
test('search matches names or contained task titles',()=>{const c=env();assert.deepEqual(ids(c.personalDesktopGridContainers('','needle')),['root']);assert.deepEqual(ids(c.personalDesktopGridContainers('root','nested')),['child']);assert.deepEqual(ids(c.personalDesktopGridContainers('','missing')),[])});
test('pagination shows at most ten items, preserving order',()=>{const c=env();const rows=Array.from({length:23},(_,id)=>({id}));assert.deepEqual(ids(c.personalDesktopGridSlice(rows,0).items),Array.from({length:10},(_,i)=>i));assert.deepEqual(ids(c.personalDesktopGridSlice(rows,2).items),[20,21,22]);assert.equal(c.personalDesktopGridSlice(rows,2).pageCount,3)});
test('pagination clamps stale and negative page numbers; empty remains valid',()=>{const c=env();assert.equal(c.personalDesktopGridSlice([],5).page,0);assert.equal(c.personalDesktopGridSlice([],-1).pageCount,1);assert.equal(c.personalDesktopGridSlice([{}],-10).page,0)});
test('reading grid does not rewrite canvas positions or nesting',()=>{const c=env(),before=JSON.stringify(c.personalLayout);c.personalDesktopGridContainers('');c.personalDesktopGridSlice(c.personalLayout.containers,1);assert.equal(JSON.stringify(c.personalLayout),before)});
test('grid has five columns; desktop-only breakpoint; guards canvas growth',()=>{assert.match(html,/grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/);assert.match(html,/function usePersonalDesktopGrid\(\).*min-width:901px/);assert.match(html,/function ensurePersonalBoardExtent[^\n]+personal-desktop-grid-board/);assert.match(html,/addEventListener\('wheel',event=>\{if\(personalMode.hidden\|\|personalBoard.classList.contains\('personal-desktop-grid-board'\)\)return/)});
test('first click is not blocked by undefined long-touch suppression',()=>{assert.match(html,/Number\(window.adibContextSuppressUntil\)\|\|0/);assert.doesNotMatch(html,/Date.now\(\)>=window.adibContextSuppressUntil/)});
