/* Display-only, per-view filters. Drafts never change tasks or applied state. */
(function(root){'use strict';
const defaults={container:'',query:'',completion:'all',status:'',priority:'',category:'',tag:'',assignee:'',source:'',process:'',dateFrom:'',dateTo:''},NONE='__empty__';
const labels={container:'Qovluq',query:'Axtarış',completion:'Vəziyyət',status:'Status',priority:'Prioritet',category:'Kateqoriya',tag:'Teq',assignee:'Məsul şəxs',source:'Baza',process:'Proses',dateFrom:'Başlanğıc tarixi',dateTo:'Bitmə tarixi'};
const personal=['container','completion','status','priority','category','tag','assignee','query','dateFrom','dateTo'];
function values(t,k){const a=k==='tag'?(t.tags||[]):k==='assignee'?(t.assignees||t.tapsirildi||[]):k==='priority'?(t.prioritet||t.priority||''):k==='source'?(t.sourceKey||''):k==='container'?(t.containerId||''):k==='process'?(t.process||t.status||''):(t[k]||'');return (Array.isArray(a)?a:[a]).map(x=>String(typeof x==='object'?(x?.name||''):x)).filter(x=>x&&x!=='.');}
function matches(t,f){const done=!!t.completed||t.status==='Done';if(f.completion==='open'&&done||f.completion==='done'&&!done)return false;for(const k of ['container','status','priority','category','tag','assignee','source','process'])if(f[k]&&(f[k]===NONE?values(t,k).length>0:!values(t,k).includes(f[k])))return false;const q=String(f.query||'').trim().toLocaleLowerCase();if(q&&![t.title,...['status','priority','category','tag','assignee','process'].flatMap(k=>values(t,k))].join(' ').toLocaleLowerCase().includes(q))return false;const date=String(t.date||'').slice(0,10);if(f.dateFrom&&(!date||date<f.dateFrom)||f.dateTo&&(!date||date>f.dateTo))return false;return true;}
function read(key,seed={}){return root.ADIBFilters.read('dialog:'+key,{...defaults,...seed});}
function open({key,title,tasks=[],containers=[],fields=personal,state,onApply,extra=[]}){const ui=root.ADIBTaskCards.dialog(title),d=ui.dialog;d.dataset.filterView=key;d.querySelector('h2').textContent='Filtrlər · '+title;d.querySelector('small').textContent='Şərtlər birlikdə tətbiq olunur. Son tətbiq olunan filtr saxlanılır.';const grid=document.createElement('div');grid.className='adib-filter-grid';ui.fields.append(grid);const controls={};let draft={...defaults,...state};
const create=(k,label,choices)=>{const wrap=document.createElement('label');wrap.textContent=label;let c;if(k==='query'||k==='dateFrom'||k==='dateTo'){c=document.createElement('input');c.type=k==='query'?'search':'date';if(k==='query')c.placeholder='Tapşırığın adı və ya xüsusiyyəti';}else{c=document.createElement('select');for(const [value,text]of choices){const o=document.createElement('option');o.value=value;o.textContent=text;c.append(o)}if(draft[k]&&!choices.some(o=>o[0]===draft[k])){const o=document.createElement('option');o.value=draft[k];o.textContent=root.ADIBAz?.label(draft[k])||draft[k];c.append(o)}}c.dataset.filterField=k;c.value=draft[k]||'';controls[k]=c;wrap.append(c);grid.append(wrap);c.addEventListener('input',preview);c.addEventListener('change',preview);};
for(const k of fields){let opts;if(k==='completion')opts=[['all','Bütün tapşırıqlar'],['open','Tamamlanmamış'],['done','Son 7 gündə icra edilib']];else if(k==='container')opts=[['','Bütün qovluqlar'],...containers.map(c=>[String(c.id),c.name||'Qovluq']),[NONE,'Qovluqsuz']];else{const rows=[...new Set(tasks.flatMap(t=>values(t,k)))].sort((a,b)=>a.localeCompare(b,'az'));opts=[['','Bütün dəyərlər'],...rows.map(v=>[v,root.ADIBTaskCards.label(v)]),[NONE,'Müəyyən edilməyib']];}create(k,labels[k],opts);}
for(const e of extra)create(e.key,e.label,e.options);const info=document.createElement('p');info.className='adib-filter-preview';ui.fields.append(info);
function collect(){for(const [k,c]of Object.entries(controls))draft[k]=c.value;return {...draft};}function preview(){const f=collect();info.textContent='Yüklənmiş tapşırıqlar üçün: '+tasks.filter(t=>root.ADIBTaskHistory.visible(t)&&matches(t,f)).length+'. Filtr tapşırıq məlumatlarını dəyişmir.';}
const b=(label,fn,cls)=>{const n=document.createElement('button');n.type='button';n.textContent=label;if(cls)n.className=cls;n.onclick=fn;return n};ui.footer.append(b('Sıfırla',()=>{for(const k of Object.keys(controls))controls[k].value=defaults[k]??extra.find(e=>e.key===k)?.default??'';preview()}),b('Ləğv et',ui.close),b('Tətbiq et',()=>{const f=collect();if(f.dateFrom&&f.dateTo&&f.dateFrom>f.dateTo){info.textContent='Başlanğıc tarixi bitmə tarixindən sonra ola bilməz.';info.setAttribute('role','alert');return;}root.ADIBFilters.write('dialog:'+key,f);onApply(f);ui.close()},'primary'));preview();d.showModal();return d;}
const api={defaults,NONE,personal,values,matches,read,open};if(typeof module==='object'&&module.exports)module.exports=api;else root.ADIBFilterDialog=api;
})(typeof window==='object'?window:globalThis);
