/* Windows workspace: a single list and the existing task editor, not a second data model. */
(function(root){'use strict';
let host,rows,status,containers,quickScopes,selected='',container='',query='',signature='',dirty=false,started=false;
const busy=new Set(),filters={showDone:true,status:''};let sort='original';
const savedHome=root.ADIBFilters.read('home',{container:'',query:'',showDone:true,status:'',sort:'original'});container=savedHome.container;query=savedHome.query;filters.showDone=savedHome.showDone;filters.status=savedHome.status;sort=['original','date','title','priority'].includes(savedHome.sort)?savedHome.sort:'original';function rememberHomeFilters(){root.ADIBFilters.write('home',{container,query,showDone:filters.showDone,status:filters.status,sort});if(typeof homeDialogFilters!=='undefined')root.ADIBFilters.write('dialog:home',{...homeDialogFilters,container,query});}

const bridge=()=>root.ADIBHomeBridge;
const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
function button(label,action,cls=''){const b=make('button',cls,label);b.type='button';b.onclick=action;return b}
const iconPaths={tasks:'M8 4h12v16H8M4 6h.01M4 12h.01M4 18h.01',day:'M4 6h16M4 12h16M4 18h10',calendar:'M4 5h16v15H4zM8 3v4M16 3v4M4 10h16',equipment:'M12 3l9 9-9 9-9-9z',chat:'M4 4h16v12H8l-4 4zM8 8h8M8 12h5',widgets:'M4 4h16v16H4zM4 10h16M10 10v10',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 3v2M12 19v2M3 12h2M19 12h2M6 6l1.5 1.5M16.5 16.5L18 18M6 18l1.5-1.5M16.5 7.5L18 6',menu:'M4 6h16M4 12h16M4 18h16'};
function icon(key){const span=make('span','adib-nav-icon');span.setAttribute('aria-hidden','true');span.innerHTML='<svg viewBox="0 0 24 24"><path d="'+iconPaths[key]+'"/></svg>';return span}
function canLeave(){const editors=[...document.querySelectorAll('#taskModal.open,.kanban-task-editor-layer,.personal-kanban-editor-layer')];if(!editors.length)return true;if(editors.some(e=>e.querySelector('#personalEditorSave:disabled,#saveTask:disabled'))){root.alert('Saxlama tamamlanana qədər gözləyin.');return false}const draft=editors.some(e=>[...e.querySelectorAll('[data-task-pane="chat"] textarea')].some(t=>t.value.trim())||e.querySelector('[data-task-pane="chat"] .adib-image-thumbs img'));return !(dirty||draft)||root.confirm('Saxlanmamış dəyişikliklər və ya qaralama var. Qənaət etmədən getmək?')}
function closeEditor(){document.getElementById('closeModal')?.click();dirty=false;selected=''}
function safeAction(fn){Promise.resolve().then(fn).catch(e=>{status.textContent='Əməliyyat uğursuz oldu: '+e.message;status.classList.add('error')})}
function leave(action){if(!canLeave())return;bridge()?.closeViews?.();closeEditor();host.hidden=true;document.body.classList.remove('adib-home-open');document.getElementById('adibHomeReturn').hidden=false;if(action)safeAction(action)}
function navAction(fn){if(!canLeave())return;bridge()?.closeViews?.();safeAction(fn)}
function chooseScope(id){if(!canLeave())return;container=String(id);rememberHomeFilters();open();render(true)}
function popup(title,build){document.querySelectorAll('.adib-home-popover').forEach(e=>e.remove());const d=make('dialog','adib-home-popover');const h=make('div','adib-home-popover-head');h.append(make('strong','',title),button('×',()=>{d.close();d.remove()}));d.append(h);build(d);document.body.append(d);d.addEventListener('cancel',()=>d.remove());d.showModal()}
function sortMenu(){popup('Sıralama',d=>{for(const [value,label]of [['original','Siyahı sırası'],['date','Tarixə görə'],['title','Adı ilə'],['priority','Prioritetlə']]){const b=button(label,()=>{sort=value;rememberHomeFilters();d.close();d.remove();render(true)},'adib-home-menu-item');b.setAttribute('aria-pressed',String(value===sort));d.append(b)}})}
let homeDialogFilters=root.ADIBFilterDialog.read('home',{status:filters.status,completion:filters.showDone?'all':'open',container,query});container=homeDialogFilters.container;query=homeDialogFilters.query;filters.status='';filters.showDone=true;
function filterMenu(){const snap=bridge().snapshot();return root.ADIBFilterDialog.open({key:'home',title:'Tapşırıqlarım',tasks:snap.tasks.filter(root.ADIBPersonalOptions.isRoot),containers:snap.containers,state:{...homeDialogFilters,container,query},onApply:f=>{homeDialogFilters=f;container=f.container;query=f.query;host.querySelector('input[type=search]').value=query;rememberHomeFilters();render(true);}});}

function ensure(){if(host)return;host=make('section','adib-home');host.id='adibHome';host.setAttribute('aria-label','Tapşırıqlarım');host.hidden=true;
 const top=make('header','adib-home-top'),title=make('div','adib-home-heading-group');title.append(make('h1','','Tapşırıqlarım'));status=make('span','adib-home-status','Saxlanan tapşırıqlar');status.setAttribute('role','status');title.append(status);top.append(title);
 const actions=make('div','adib-home-top-actions');const refresh=button('↻',event=>safeAction(()=>bridge().refresh(!!event.shiftKey)),'adib-home-refresh');refresh.title='Tapşırıqlarımı yeniləyin. Shift — tam uzlaşma';refresh.setAttribute('aria-label','Tapşırıqları yeniləyin');const sortButton=button('Sıralama',sortMenu,'adib-home-sort'),filter=button('Filtr',filterMenu,'adib-home-filter'),add=button('+ Tapşırıq',addMenu,'adib-home-add');add.setAttribute('aria-label','Tapşırıq əlavə et');actions.append(refresh,sortButton,filter,add);top.append(actions);host.append(top);
 const layout=make('div','adib-home-layout'),side=make('aside','adib-home-side');side.id='adibPersistentSide';
 const sideTop=make('div','adib-side-top'),brand=make('div','adib-side-brand');brand.append(make('span','','A'),make('strong','','ADIB'));
 const toggle=button('',()=>{const collapsed=document.body.classList.toggle('adib-side-collapsed');localStorage.setItem('adib-side-collapsed',String(collapsed));toggle.setAttribute('aria-expanded',String(!collapsed))},'adib-side-toggle');toggle.append(icon('menu'));toggle.setAttribute('aria-label','Sol paneli yığcamlaşdırın və ya genişləndirin');toggle.setAttribute('aria-expanded',String(localStorage.getItem('adib-side-collapsed')!=='true'));sideTop.append(brand,toggle);side.append(sideTop,make('small','adib-home-heading','İŞ SAHASI'));
 for(const [key,label,action]of [['tasks','Tapşırıqlarım',()=>open()],['day','Gün planı',()=>navAction(()=>bridge().day())],['calendar','Təqvim',()=>navAction(()=>root.ADIBCalendar.open())],['equipment','Avadanlıq',()=>leave(()=>bridge().canvas())],['chat','Müzakirələr',()=>navAction(()=>root.openCommentChat?.())]]){const b=button('',action,'adib-home-nav');b.dataset.homeNav=key;b.append(icon(key),make('span','',label));side.append(b)}
 side.append(make('small','adib-home-heading','QOVLUQLAR'));containers=make('nav','adib-home-containers');containers.setAttribute('aria-label','Qovluqlar');side.append(containers);
 const tools=make('details','adib-home-tools');tools.append(make('summary','','Digər görünüşlər'));tools.append(button('Kanban',()=>navAction(()=>bridge().kanban())),button('Eyzenhauer matrisi',()=>navAction(()=>bridge().matrix())),button('Tapşırıqlarımın təsviri',()=>leave(()=>bridge().personalCanvas())));side.append(tools);
 const sideBottom=make('div','adib-side-bottom');for(const [key,label,action]of [['widgets','Vidjetlər',()=>root.ADIBWidgetHub.openMenu()],['settings','Ayarlar',()=>{if(root.ADIBDesktop?.openSettings)void root.ADIBDesktop.openSettings().catch(e=>root.alert(e.message));else document.getElementById('adibSettingsButton')?.click()}]]){const b=button('',action,'adib-home-nav');b.append(icon(key),make('span','',label));sideBottom.append(b)}
 sideBottom.append(button('Açıq / tünd mövzu',()=>{const dark=!document.documentElement.classList.contains('dark');localStorage.setItem('ela-theme',dark?'dark':'light');root.setTheme?.(dark)},'adib-home-theme'));const clock=button('◷ Şəbəkə vaxtı',()=>root.ADIBClock?.details(),'adib-home-clock');sideBottom.append(clock);side.append(sideBottom);
 document.body.classList.add('adib-side-ready');document.body.classList.toggle('adib-side-collapsed',localStorage.getItem('adib-side-collapsed')==='true');document.body.append(side);root.ADIBClock?.attach();
 const list=make('section','adib-home-list');list.setAttribute('aria-label','Tapşırıqlarımın siyahısı');const input=make('input','adib-home-search');input.type='search';input.value=query;input.placeholder='Tapşırıqları axtarın…';input.setAttribute('aria-label','Tapşırıqları axtarın');input.oninput=()=>{query=input.value;rememberHomeFilters();render(true)};list.append(input);quickScopes=make('nav','adib-home-quick-scopes');quickScopes.setAttribute('aria-label','Sürətli konteynerlər');list.append(quickScopes);const scope=make('div','adib-home-scope');scope.id='adibHomeScope';list.append(scope);rows=make('div','adib-home-rows');rows.setAttribute('aria-label','Tapşırıq siyahısı');list.append(rows);
 const detail=make('section','adib-home-detail');detail.append(make('h2','','Tapşırıq seçin'),make('p','','Xüsusiyyətləri, təsviri və alt tapşırıqları açmaq üçün soldakı başlığa klikləyin.'));layout.append(list,detail);host.append(layout);document.body.append(host);
 const back=button('← Tapşırıqlarım',()=>open(),'adib-home-return');back.id='adibHomeReturn';back.hidden=true;document.body.append(back);
 const modal=document.getElementById('taskModal');new MutationObserver(dock).observe(modal,{attributes:true,attributeFilter:['class','data-personal-editor']});new MutationObserver(()=>{dirty=false;dock()}).observe(document.getElementById('taskList'),{childList:true});modal.addEventListener('input',()=>{dirty=true});modal.addEventListener('change',()=>{dirty=true});modal.addEventListener('adib-autostored',()=>dirty=false);modal.addEventListener('adib-autosaved',()=>dirty=false);root.addEventListener('adib-home-data',()=>render(true));root.addEventListener('adib-home-status',()=>setTimeout(()=>render(false),0));setInterval(()=>{if(!host.hidden)render(false)},1000);
}
function dock(){if(!host)return;const modal=document.getElementById('taskModal'),opened=modal?.classList.contains('open')&&modal.dataset.personalEditor==='1'&&!host.hidden;modal?.classList.toggle('adib-home-docked',!!opened);if(!opened){dirty=false;host.classList.remove('has-task')}else host.classList.add('has-task')}
function addMenu(){if(!canLeave())return;const dialog=make('dialog','adib-home-add-menu');dialog.append(make('h2','','Tapşırıq əlavə et'));for(const [label,key]of [['Tapşırıqlarım → INBOX','personal'],['ToDo','todo'],['Gorulen isler','gorulen']])dialog.append(button(label,()=>{dialog.close();dialog.remove();closeEditor();if(key==='personal')safeAction(()=>bridge().newTask(container?{containerId:container}:undefined));else leave(()=>{const task=root.newTaskDraft();task.sourceKey=key;root.openTaskEditor(task,null,true)})}));dialog.append(button('Ləğv et',()=>{dialog.close();dialog.remove()}));dialog.addEventListener('cancel',()=>dialog.remove());document.body.append(dialog);dialog.showModal()}
function open(){started=true;ensure();root.ADIBCalendar?.close();if(!canLeave())return;bridge()?.closeViews?.();closeEditor();if(host.hidden){document.querySelectorAll('.personal-kanban-modal,.personal-eisenhower-modal').forEach(e=>e.remove());host.hidden=false;document.body.classList.add('adib-home-open');document.getElementById('adibHomeReturn').hidden=true;safeAction(()=>bridge().activate())}render(true);dock();return Promise.resolve()}
function render(force){if(!host||host.hidden||!bridge())return;const s=bridge().snapshot();status.textContent=s.error||(s.busy?'Yenilənir… Saxlanmış tapşırıqlar mövcuddur.':s.updatedAt?'Yenilənib '+(root.ADIBClock?.fromSystemTimestamp(s.updatedAt)||new Date(s.updatedAt)).toLocaleTimeString('az',{hour:'2-digit',minute:'2-digit'})+(root.ADIBClock?.trusted?' · şəbəkə vaxtı':''):s.ready?'Saxlanmış tapşırıqlar göstərilir':'Tapşırıqların ilk yüklənməsi…');status.classList.toggle('error',!!s.error);const refresh=host.querySelector('.adib-home-refresh');refresh.disabled=s.busy;refresh.textContent=s.busy?'…':'↻';host.querySelector('.adib-home-filter').classList.toggle('active',Object.entries(homeDialogFilters).some(([k,v])=>k==='completion'?v!=='all':!!v));document.querySelector('[data-home-nav="tasks"]')?.classList.add('active');
 const clock=document.querySelector('.adib-home-clock');if(clock)clock.textContent='◷ '+(root.ADIBClock?.trusted?'Şəbəkə vaxtı · '+root.ADIBClock.date().toLocaleTimeString('az',{hour:'2-digit',minute:'2-digit'}):'Şəbəkə vaxtı gözlənilir');
 if(container&&container!==root.ADIBFilterDialog.NONE&&s.ready&&!s.busy&&!s.error&&!s.containers.some(c=>String(c.id)===container)){container='';rememberHomeFilters();}const key=JSON.stringify([s.tasks,s.containers,container,query,s.ready,sort,filters,selected]);if(!force&&key===signature)return;signature=key;
 containers.replaceChildren();for(const c of [{id:'',name:'Bütün tapşırıqlar'},...s.containers]){const b=button(c.name||'Qovluq',()=>chooseScope(c.id),'adib-home-container');b.dataset.homeContainer=c.id;b.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-adib-task')){e.preventDefault();e.dataTransfer.dropEffect='move';b.classList.add('drop-target')}});b.addEventListener('dragleave',()=>b.classList.remove('drop-target'));b.addEventListener('drop',e=>{e.preventDefault();b.classList.remove('drop-target');const id=e.dataTransfer.getData('application/x-adib-task');if(id)safeAction(()=>bridge().patch(id,{containerId:String(c.id)}))});b.classList.toggle('active',!!container&&String(c.id)===container);containers.append(b)}
 quickScopes.replaceChildren();const quick=[{id:'',name:'Hamısı'},...s.containers.filter(c=>['inbox','my day'].includes(String(c.name).trim().toLowerCase()))];if(container&&!quick.some(c=>String(c.id)===container)){const c=s.containers.find(c=>String(c.id)===container);if(c)quick.push(c)}for(const c of quick){const b=button(c.name,()=>chooseScope(c.id));b.dataset.quickContainer=c.id;b.setAttribute('aria-pressed',String(String(c.id)===container));quickScopes.append(b)}
 const all=s.tasks||[],visible=all.filter(t=>!t.parentId&&root.ADIBTaskHistory.visible(t)&&root.ADIBFilterDialog.matches(t,{...homeDialogFilters,container,query})&&(filters.showDone||!t.completed)&&(!filters.status||t.status===filters.status)&&(!container||(container===root.ADIBFilterDialog.NONE?!t.containerId:String(t.containerId||'')===container)));
 if(sort==='title')visible.sort((a,b)=>String(a.title).localeCompare(String(b.title),'az'));if(sort==='date')visible.sort((a,b)=>(Date.parse(a.date)||Infinity)-(Date.parse(b.date)||Infinity));if(sort==='priority')visible.sort((a,b)=>String(b.prioritet||'').replace(/[^!]/g,'').length-String(a.prioritet||'').replace(/[^!]/g,'').length);
 document.getElementById('adibHomeScope').textContent=(s.containers.find(c=>String(c.id)===container)?.name||'Bütün tapşırıqlar')+' · '+visible.length;
 const scroll=rows.scrollTop,childCounts=new Map();for(const child of [...new Map([...(s.graph||all),...all].map(t=>[t.id,t])).values()])if(child.parentId)childCounts.set(String(child.parentId),(childCounts.get(String(child.parentId))||0)+1);rows.replaceChildren();for(const task of visible){const card=make('article','adib-home-row adib-task-card');card.draggable=true;card.addEventListener('dragstart',e=>{if(e.target.closest('button,select,input,a')){e.preventDefault();return}e.dataTransfer.setData('application/x-adib-task',String(task.id));e.dataTransfer.effectAllowed='move'});card.dataset.personalTask=task.id;card.dataset.homeTask=task.id;card.classList.toggle('active',String(task.id)===selected);card.classList.toggle('completed',!!task.completed);
 const count=childCounts.get(String(task.id))||0,total=root.ADIBPomodoroRollup.totals(task,s.graph||all),name=s.containers.find(c=>String(c.id)===String(task.containerId))?.name||'Qovluqsuz',done=!!task.completed||task.status==='Done';card.classList.toggle('completed',done);card.innerHTML=root.ADIBTaskCards.content({title:task.title,done,checkClass:'adib-home-check',titleAttrs:'data-home-open="'+root.ADIBTaskCards.escape(task.id)+'"',meta:[name,count?count+' '+root.ADIBTaskCards.subtaskLabel(count):''].filter(Boolean).join(' · '),chips:[{text:task.status,kind:'status'},task.prioritet&&task.prioritet!=='.'?task.prioritet:'',task.date?root.ADIBPersonalWorkspace?.formatDate(task.date)||String(task.date).split('T')[0]:''],timer:root.personalPomodoroIndicatorForTask?.(task,true)||root.ADIBTaskCards.totals(total.count,total.minutes)});
 const check=card.querySelector('.adib-home-check');check.disabled=busy.has(task.id);check.onclick=e=>{e.stopPropagation();if(!canLeave()||busy.has(task.id))return;busy.add(task.id);check.disabled=true;safeAction(async()=>{try{await bridge().patch(task.id,{completed:!done,status:done?'Not started':'Done'});if(selected===String(task.id))closeEditor();render(true)}finally{busy.delete(task.id);check.disabled=false}})};
 const main=card.querySelector('[data-home-open]');main.onclick=()=>{if(!canLeave())return;closeEditor();selected=String(task.id);safeAction(()=>{bridge().openTask(task.id);dock();render(true)})};card.onclick=e=>{if(!e.target.closest('button,select,input,a'))main.click()};rows.append(card)}
 if(!visible.length)rows.append(make('p','adib-home-empty',query||filters.status||!filters.showDone?'Heç nə tapılmadı':s.ready?'Hələlik tapşırıq yoxdur. “ klikləyin+ Tapşırıq“ əlavə etmək üçün.':'Tapşırıqlar yüklənir…'));rows.scrollTop=scroll;
}
root.ADIBHome={open,leave,canLeave,get started(){return started}};
})(window);
