(function(root){'use strict';
 const drafts=new Map(),busy=new Set(),MAX=5*1024*1024;let sendApi=null;
 async function api(path,body){if(sendApi)return sendApi(path,body===undefined?undefined:{method:'POST',body:JSON.stringify(body)});const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'Ошибка загрузки изображения · HTTP '+r.status);return data}
 function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
 function imageMarkup(list){return '<div class="adib-image-thumbs">'+(list||[]).filter(x=>safeUrl(x.url)).map(x=>'<span><button type="button" data-adib-show-photo="'+escape(safeUrl(x.url))+'">📷 Показать фото</button><a target="_blank" rel="noopener noreferrer" href="'+escape(safeUrl(x.url))+'">Оригинал</a></span>').join('')+'</div>'}
 if(typeof document!=='undefined')document.addEventListener('click',e=>{const button=e.target.closest?.('[data-adib-show-photo]');if(!button||button.disabled)return;const url=button.dataset.adibShowPhoto;const img=document.createElement('img');img.referrerPolicy='no-referrer';img.crossOrigin='anonymous';let retried=false;img.alt='Фото';img.onload=()=>remember(url,img);img.onerror=()=>{if(!retried){retried=true;img.removeAttribute('crossorigin');img.src=safeUrl(url);return;}img.remove();button.disabled=false;button.textContent='Обновите фото и повторите'};img.src=thumbnailCache.get(cacheKey(url))||safeUrl(url);button.parentElement.append(img);button.disabled=true;});

 function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 const TARGET=200*1024,MAX_INPUT=30*1024*1024;
 async function compressPhoto(file){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Error('Выберите JPG, PNG, WEBP или GIF');if(file.size>MAX_INPUT)throw Error('Фото должно быть не больше 30 МБ');if(file.size<=TARGET)return file;const url=URL.createObjectURL(file);let img;try{img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Не удалось прочитать фото'));i.src=url});if(img.naturalWidth*img.naturalHeight>100000000)throw Error('Слишком большое разрешение фотографии');let scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement('canvas');let blob;for(let step=0;step<16;step++){canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);for(const q of [.82,.70,.58,.46]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',q));if(blob&&blob.size<=TARGET)return new File([blob],file.name.replace(/\.[^.]*$/,'')+'.jpg',{type:'image/jpeg'});}scale*=.75;}throw Error('Не удалось уменьшить фотографию до 200 КБ');}finally{URL.revokeObjectURL(url);}}
 async function imageData(file){file=await compressPhoto(file);const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Не удалось прочитать файл'));reader.readAsDataURL(file)});return {name:file.name,mime:file.type,data}}

 function clear(key){busy.delete(key);for(const item of drafts.get(key)||[])if(item.preview)URL.revokeObjectURL(item.preview);drafts.delete(key);document.querySelectorAll("[data-image-picker]").forEach(box=>{if(box.dataset.imagePicker===key)box.querySelector(".adib-image-thumbs")?.replaceChildren()})}
 function has(key){return Boolean(drafts.get(key)?.length)}
 async function uploads(key){busy.add(key);const list=drafts.get(key)||[],result=[];for(const item of list){if(!item.upload||Date.now()-item.uploadAt>50*60000){item.upload=await api('/api/image-upload',{image:await imageData(item.file)});item.uploadAt=Date.now()}result.push({type:'file_upload',file_upload_id:item.upload.fileUploadId})}return result}
 function picker(container,key){if(!container||container.querySelector('[data-image-picker]'))return;const box=document.createElement('div');box.dataset.imagePicker=key;box.className='adib-image-picker';const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/gif';input.multiple=true;input.hidden=true;input.dataset.commentImages='true';const add=document.createElement('button');add.type='button';add.textContent='📷 Изображения';const preview=document.createElement('div');preview.className='adib-image-thumbs';const status=document.createElement('small');status.setAttribute('role','status');
 const render=()=>{preview.replaceChildren();for(const item of drafts.get(key)||[]){const wrap=document.createElement('span'),img=document.createElement('img'),remove=document.createElement('button');img.src=item.preview;img.alt=item.file.name;remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Убрать изображение');remove.onclick=()=>{if(busy.has(key))return;const list=drafts.get(key)||[];drafts.set(key,list.filter(x=>x!==item));URL.revokeObjectURL(item.preview);render()};wrap.append(img,remove);preview.append(wrap)}};
 add.onclick=()=>{if(!busy.has(key))input.click()};input.onchange=async()=>{if(busy.has(key)){input.value='';return}const files=Array.from(input.files||[]),old=drafts.get(key)||[];if(old.length+files.length>3){status.textContent='До 3 изображений в одном комментарии';input.value='';return}try{busy.add(key);status.textContent='Подготовка фото…';const ready=[];for(const file of files)ready.push(await compressPhoto(file));drafts.set(key,[...old,...ready.map(file=>({file,preview:URL.createObjectURL(file)}))]);status.textContent='Готово: '+ready.map(f=>Math.ceil(f.size/1024)+' КБ').join(', ')+'. Отправятся с комментарием';render()}catch(e){status.textContent=e.message}finally{busy.delete(key)};input.value=''};box.append(add,input,status,preview);container.append(box);render()}
 function taskPanel(container,id){if(!container)return;const old=container.querySelector('.adib-task-images');if(old)old.remove();const box=document.createElement('section');box.className='adib-task-images';box.innerHTML='<strong>Изображения задачи</strong>';const gallery=document.createElement('div'),status=document.createElement('small'),add=document.createElement('button'),refresh=document.createElement('button'),input=document.createElement('input');status.setAttribute('role','status');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/gif';input.multiple=true;input.hidden=true;input.dataset.taskImages='true';add.type=refresh.type='button';add.textContent='📷 Добавить изображение';refresh.textContent='Обновить изображения';
 const load=async()=>{try{const result=await api('/api/task-images?id='+encodeURIComponent(id));if(!box.isConnected)return;gallery.innerHTML=imageMarkup(result.images||[]);status.textContent=result.images?.length?'':'Изображений пока нет'}catch(e){if(box.isConnected)status.textContent='Не удалось загрузить изображения. '+e.message}};
 add.onclick=()=>input.click();refresh.onclick=()=>void load();if(!id){add.disabled=refresh.disabled=true;status.textContent='Сначала сохраните задачу, затем добавьте изображение'}
 input.onchange=async()=>{const files=Array.from(input.files||[]);add.disabled=refresh.disabled=true;try{for(const file of files){status.textContent='Загружаю '+file.name+'…';const uploaded=await api('/api/image-upload',{image:await imageData(file)});await api('/api/task-image',{id,fileUploadId:uploaded.fileUploadId})}await load();if(box.isConnected)status.textContent='Изображения сохранены в Notion'}catch(e){if(box.isConnected)status.textContent='Не удалось прикрепить: '+e.message}finally{input.value='';if(box.isConnected)add.disabled=refresh.disabled=false}};box.append(gallery,add,refresh,input,status);container.append(box);if(id)void load();return box}
 const thumbnailCache=new Map();let thumbnailBytes=0;
 function cacheKey(url){let owner=(root.ADIBAccount?.user?(root.ADIBAccount.user.id+':'+root.ADIBAccount.user.revision):'local');return owner+':'+url.split('?')[0];}
 function remember(url,img){try{const c=document.createElement('canvas');const scale=Math.min(1,320/Math.max(img.naturalWidth,img.naturalHeight));c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);const data=c.toDataURL('image/jpeg',.65),key=cacheKey(url);if(thumbnailCache.has(key))thumbnailBytes-=thumbnailCache.get(key).length;thumbnailCache.delete(key);thumbnailCache.set(key,data);thumbnailBytes+=data.length;while(thumbnailCache.size>50||thumbnailBytes>3*1024*1024){const k=thumbnailCache.keys().next().value;thumbnailBytes-=thumbnailCache.get(k).length;thumbnailCache.delete(k);}}catch{} }
 function photoRow(container,item,onRemove){const row=document.createElement('div'),show=document.createElement('button'),open=document.createElement('a');show.type='button';show.textContent='📷 '+(item.name||'Фото')+' · Показать';open.textContent='Открыть оригинал';open.href=safeUrl(item.url);open.target='_blank';open.rel='noopener noreferrer';open.referrerPolicy='no-referrer';row.append(show,open);if(onRemove&&(!root.ADIBAccount||root.ADIBAccount.action('delete'))){const remove=document.createElement('button');remove.type='button';remove.textContent='Удалить';remove.onclick=onRemove;row.append(remove);}show.onclick=()=>{const img=document.createElement('img');img.alt=item.name||'Фото';img.style.cssText='display:block;max-width:100%;max-height:240px';img.referrerPolicy='no-referrer';img.crossOrigin='anonymous';let retried=false;img.onload=()=>remember(item.url,img);img.onerror=()=>{if(!retried){retried=true;img.removeAttribute('crossorigin');img.src=safeUrl(item.url);return;}img.remove();show.disabled=false;show.textContent='Не удалось открыть. Обновите ссылки на фото.'};img.src=thumbnailCache.get(cacheKey(item.url))||safeUrl(item.url);show.disabled=true;row.append(img);};container.append(row);}
 function photoFields(container,id){if(!container||container.querySelector('.adib-photo-fields'))return;const box=document.createElement('section');box.className='adib-photo-fields';const status=document.createElement('small');status.setAttribute('role','status');container.append(box);box.append(status);if(!id){status.textContent='Foto evvel / Foto sonra: сначала сохраните задачу';return box;}let state;
 const render=()=>{box.replaceChildren();for(const field of ['Foto evvel','Foto sonra']){const data=state.fields[field],section=document.createElement('section'),title=document.createElement('h4'),gallery=document.createElement('div'),add=document.createElement('button'),input=document.createElement('input');title.textContent=field;input.type='file';input.accept='image/*';input.multiple=true;input.hidden=true;add.type='button';add.textContent='📷 Добавить фото';add.disabled=!data.available||(root.ADIBAccount&&!root.ADIBAccount.action('edit'));add.onclick=()=>input.click();section.append(title,gallery,add,input);for(const image of data.images)photoRow(gallery,image,()=>{if(!confirm('Удалить фото из поля '+field+'?'))return;void run(()=>api('/api/task-photo',{id,field,remove:true,index:image.index,version:data.version}));});input.onchange=async()=>{const files=Array.from(input.files||[]);add.disabled=true;try{for(const file of files){status.textContent='Подготовка фото…';const image=await imageData(file);status.textContent='Загрузка сжатого фото…';const u=await api('/api/image-upload',{id,image});state=await api('/api/task-photo',{id,field,fileUploadId:u.fileUploadId});}render();status.textContent='Фото сохранены в Notion'}catch(e){status.textContent=e.message+' Обновите фото перед повторной отправкой.'}finally{input.value='';add.disabled=false}};box.append(section);}if(Object.values(state.fields).some(f=>!f.available)&&(!root.ADIBAccount?.user||root.ADIBAccount.user.role==='admin')){const init=document.createElement('button');init.type='button';init.textContent='Создать поля в Notion (администратор)';init.onclick=()=>void run(()=>api('/api/task-photo-schema',{id}));box.append(init);}const refresh=document.createElement('button');refresh.type='button';refresh.textContent='Обновить фото';refresh.onclick=()=>void run(()=>api('/api/task-photos?id='+encodeURIComponent(id)));box.append(refresh,status);};
 const run=async job=>{box.querySelectorAll('button').forEach(b=>b.disabled=true);try{state=await job();if(!box.isConnected)return;if(!state.supported){box.remove();return;}render();status.textContent='Фото загружаются только по нажатию «Показать».'}catch(e){status.textContent=e.message;box.querySelectorAll('button').forEach(b=>b.disabled=false);}};void run(()=>api('/api/task-photos?id='+encodeURIComponent(id)));return box;}
 root.ADIBImages={setApi:fn=>sendApi=fn,unlock:key=>busy.delete(key),taskPanel,photoFields,compressPhoto,picker,uploads,has,clear,imageMarkup,safeUrl,imageData};
})(globalThis);
