(function(root){'use strict';let anchor=null,state={trusted:false},inflight;const api=root.ADIBDesktop;
function now(){return anchor?anchor.epoch+performance.now()-anchor.mono:Date.now()}
function date(){return new Date(now())}
function accept(s){if(!s)return;state=s;if(s.trusted)anchor={epoch:s.now,mono:performance.now()};root.dispatchEvent(new Event('adib-clock-change'));renderNotice()}
function report(){const f=n=>new Date(n).toLocaleString('ru-RU');return ['ADIB — сведения для администратора','Часовой пояс: '+(state.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone),'Сетевое время: '+(anchor?f(now()):'не подтверждено'),'Время компьютера: '+f(Date.now()),'Разница: '+Math.round((now()-Date.now())/1000)+' секунд','Источник: '+(state.source||'часы компьютера'),'Последняя сверка: '+(state.checkedAt||'нет'),'Проверьте дату, часовой пояс и синхронизацию Windows. ADIB не меняет системные часы.'].join('\n')}
function details(){const dialog=document.createElement('dialog');dialog.className='adib-clock-dialog';const title=document.createElement('h2');title.textContent='Дата и время';const text=document.createElement('textarea');text.readOnly=true;text.value=report();const copy=document.createElement('button');copy.textContent='Скопировать для администратора';copy.onclick=async()=>{try{await navigator.clipboard.writeText(text.value);copy.textContent='Скопировано'}catch{text.focus();text.select();copy.textContent='Выделено — нажмите Ctrl+C'}};const sync=document.createElement('button');sync.textContent='Сверить сейчас';sync.onclick=async()=>{sync.disabled=true;await refresh(true);text.value=report();sync.disabled=false};const close=document.createElement('button');close.textContent='Закрыть';close.onclick=()=>{dialog.close();dialog.remove()};dialog.append(title,text,copy,sync,close);dialog.oncancel=()=>dialog.remove();document.body.append(dialog);dialog.showModal()}
function renderNotice(){if(!api?.getTime||!document.body)return;let box=document.getElementById('adibClockNotice');if(!box){box=document.createElement('button');box.id='adibClockNotice';box.onclick=details;box.type='button';document.body.append(box)}const skew=Math.round((now()-Date.now())/1000);box.hidden=!!anchor&&Math.abs(skew)<120&&!state.error;box.textContent=anchor?(state.error?'Нет связи с источником времени. Использую последние сверенные часы.': 'Часы компьютера отличаются от сетевых. Сведения для администратора'):'Сетевое время пока не подтверждено. Проверить часы';box.title=report();const side=document.getElementById('adibPersistentSide');if(side&&box.parentElement!==side)side.append(box)}
async function refresh(force=false){if(!api?.getTime)return state;if(inflight)return inflight;inflight=(force&&api.syncTime?api.syncTime():api.getTime()).then(accept).catch(()=>{state.error='Нет связи с источником времени';renderNotice()}).finally(()=>inflight=null);return inflight}
root.ADIBClock={now,date,fromSystemTimestamp:value=>new Date(Number(value)+(anchor?now()-Date.now():0)),refresh,details,report,attach:renderNotice,get trusted(){return !!anchor},get state(){return state}};api?.onTime?.(accept);void refresh();root.addEventListener('DOMContentLoaded',renderNotice);root.addEventListener('adib-home-data',renderNotice);let day='';setInterval(()=>{renderNotice();const key=date().toDateString();if(day&&key!==day)root.dispatchEvent(new Event('adib-clock-change'));day=key},60000);
})(window);
