(function(root){'use strict';const mono=()=>performance.now();let anchor=null,inflight=null,timeZone='Asia/Baku',state={trusted:false,timeZone,policy:'network-only'},resolveReady,lastDay='';const ready=new Promise(r=>resolveReady=r);
function now(){return anchor&&mono()-anchor.mono<anchor.maxAge?anchor.epoch+Math.max(0,mono()-anchor.mono):NaN;}
function date(){return new root.ADIBZone.ZonedDate(now(),timeZone);}
function stamp(){const at=now();return Number.isFinite(at)?at:mono();} // Monotonic UI/cache counters, never a civil-time fallback.
function accept(s,rtt=0){if(s?.timeZone){new Intl.DateTimeFormat('en',{timeZone:s.timeZone});timeZone=s.timeZone;}state={...state,...s,timeZone};if(s?.trusted&&Number.isFinite(s.now)){anchor={epoch:s.now+rtt/2,mono:mono(),maxAge:Math.max(0,(s.maxAgeMs||86400000)-(s.ageMs||0))};resolveReady();}
 state.trusted=Number.isFinite(now());root.dispatchEvent(new Event('adib-clock-change'));root.dispatchEvent(new Event('adib-home-data'));notice();}
function report(){const d=date();return ['ADIB Online 1.1.42 — yalnız şəbəkə vaxtı','Tətbiq vaxtı zonası: '+timeZone,'Cari vaxt: '+(Number.isFinite(now())?d.toLocaleString('az-AZ'):'hələ təsdiqlənməyib'),'Mənbə: '+(state.source||'gözlənilir'), 'Son uzlaşma: '+(state.checkedAt?new root.ADIBZone.ZonedDate(Date.parse(state.checkedAt),timeZone).toLocaleString('az-AZ'):'nömrə'),state.holdover?'Bağlantı yoxdur: son şəbəkə uzlaşmasından geri sayım davam edir.':'',state.error||'','Kompüterin saatı və saat qurşağı istifadə edilmir.'].filter(Boolean).join('\n');}
function details(){const dialog=document.createElement('dialog');dialog.className='adib-clock-dialog';const title=document.createElement('h2');title.textContent='Şəbəkə vaxtı';const text=document.createElement('textarea');text.readOnly=true;text.value=report();const sync=document.createElement('button');sync.textContent='İndi yoxlayın';sync.onclick=async()=>{sync.disabled=true;await refresh(true);text.value=report();sync.disabled=false};const close=document.createElement('button');close.textContent='Bağla';close.onclick=()=>{dialog.close();dialog.remove()};dialog.append(title,text,sync,close);dialog.oncancel=()=>dialog.remove();document.body.append(dialog);dialog.showModal();}
function notice(){if(!document.body)return;let box=document.getElementById('adibClockNotice');if(!box){box=document.createElement('button');box.id='adibClockNotice';box.onclick=details;document.body.append(box);}box.hidden=Number.isFinite(now())&&!state.error&&!state.holdover;box.textContent=Number.isFinite(now())?'Vaxt mənbəyi ilə əlaqə yoxdur. Son şəbəkə uzlaşmasından geri sayım.':'Şəbəkə vaxtı hələ təsdiqlənməyib. Bağlantı yoxlayın';box.title=report();const side=document.getElementById('adibPersistentSide');if(side&&box.parentElement!==side)side.append(box);
 let wait=document.getElementById('adibTimeWait');if(!Number.isFinite(now())){if(!wait){wait=document.createElement('section');wait.id='adibTimeWait';wait.innerHTML='<div><h2>Şəbəkə vaxtını təsdiq edirəm</h2><p>Kompüter saatı istifadə edilmir. İlk işə salmaq üçün serverə və vaxt mənbəyinə qoşulmalısınız.</p><button type="button">Yenidən cəhd et</button><p role="status"></p></div>';wait.querySelector('button').onclick=()=>refresh(true);document.body.append(wait);}wait.querySelector('[role="status"]').textContent=state.error||'Sinxronizasiya…';}else wait?.remove();}
async function refresh(force=false){if(inflight)return inflight;inflight=(async()=>{const before=mono(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('/api/time'+(force?'?force=1':''),{cache:'no-store',signal:controller.signal});const s=await r.json();if(!r.ok||!s.trusted||!Number.isFinite(s.now))throw Error(s.error||'Şəbəkə vaxtı hələ təsdiqlənməyib');accept(s,Math.max(0,mono()-before-Number(s.processingMs||0)));return state;}catch(e){state={...state,error:'Təsdiqlənmiş şəbəkə uzlaşması yoxdur',holdover:!!anchor,trusted:Number.isFinite(now())};notice();return state;}finally{clearTimeout(timer);}})().finally(()=>inflight=null);return inflight;}
root.ADIBClock={now,date,stamp,elapsed:mono,ready,refresh,details,report,attach:notice,fromSystemTimestamp:value=>new root.ADIBZone.ZonedDate(Number(value),timeZone),get trusted(){return Number.isFinite(now());},get timeZone(){return timeZone;},get state(){return {...state,trusted:Number.isFinite(now()),timeZone};}};
void refresh();root.addEventListener('DOMContentLoaded',notice);root.addEventListener('adib-home-data',notice);root.addEventListener('pageshow',()=>refresh(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh(true)});root.addEventListener('online',()=>refresh(true));setInterval(()=>{notice();const day=date().toDateString();if(lastDay&&day!==lastDay&&Number.isFinite(now()))root.dispatchEvent(new Event('adib-clock-change'));lastDay=day;},15000);setInterval(()=>refresh(),60000);
})(window);
