const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const html=fs.readFileSync(__dirname+'/ela-nov-paketleme-dynamic.html','utf8');
const code=html.slice(html.indexOf('function removePlanBoardTask('),html.indexOf('function openPlanTasks('));
function env(){const state={plans:[{id:'root',tasks:[{id:'own'}]},{id:'child',parentId:'root',tasks:[{id:'childTask'}]},{id:'deep',parentId:'child',tasks:[{id:'deepTask'}]},{id:'other',tasks:[{id:'otherTask'}]}],equipment:[{id:'pump',planId:'deep',tasks:[{id:'pumpTask'}]},{id:'outside',planId:'other',tasks:[{id:'outsideTask'}]}]};const c=vm.createContext({state,taskSourceLabel:k=>k});vm.runInContext(code,c);return c;}
const ids=tasks=>Array.from(tasks,t=>t.id).sort();
test('web list includes own, deep plans and their equipment; excludes unrelated tasks',()=>{const c=env();assert.deepEqual(ids(c.planBoardTasks('root')),['childTask','deepTask','own','pumpTask']);assert.deepEqual(ids(c.planBoardTasks('child')),['childTask','deepTask','pumpTask']);});
test('web plan aggregation deduplicates IDs',()=>{const c=env();c.state.equipment[0].tasks.push({id:'own'});assert.equal(c.planBoardTasks('root').filter(t=>t.id==='own').length,1);});
test('plan-only task retains real child owner and no machine',()=>{const c=env();const t=c.planBoardTasks('root').find(t=>t.id==='deepTask');assert.equal(t.planId,'deep');assert.equal(t.machineId,'');assert.equal(c.taskMachineForBoard(t,{isPlanBoard:true}),null);});
test('machine task opens actual equipment owner',()=>{const c=env();const t=c.planBoardTasks('root').find(t=>t.id==='pumpTask');assert.equal(c.taskMachineForBoard(t,{isPlanBoard:true}).id,'pump');});
test('refresh recalculates membership, including newly nested equipment',()=>{const c=env();const board={isPlanBoard:true,planId:'root',machineIds:[]};c.state.equipment.push({id:'new',planId:'child',tasks:[{id:'newTask'}]});c.refreshKanbanBoardData(board);assert.ok(ids(board.tasks).includes('newTask'));assert.ok(board.machineIds.includes('new'));});
test('plan cycles do not loop forever',()=>{const c=env();c.state.plans[0].parentId='deep';assert.equal(c.planBoardPlanIds('root').size,3);});
test('saving direct task moves it to selected real plan rather than aggregate root',()=>{const c=env();const t=c.planBoardTasks('root').find(t=>t.id==='deepTask');c.applyPlanBoardTaskSave(t,{machineId:'',planId:'child',sourceKey:'todo',title:'Changed',process:'In progress',completed:false},{},t.id);assert.equal(c.state.plans[2].tasks.length,0);assert.equal(c.state.plans[1].tasks[0].title,'Changed');assert.equal(c.state.plans[0].tasks.length,1);});
test('completing/deleting direct task removes canonical backing entry',()=>{const c=env();const t=c.planBoardTasks('root').find(t=>t.id==='deepTask');c.applyPlanBoardTaskSave(t,{machineId:'',planId:'deep',sourceKey:'todo',process:'Done',completed:true},{},t.id);assert.ok(!ids(c.planBoardTasks('root')).includes('deepTask'));c.removePlanBoardTask('pumpTask');assert.ok(!ids(c.planBoardTasks('root')).includes('pumpTask'));});
test('status changes sync to backing direct task',()=>{const c=env();const t=c.planBoardTasks('root').find(t=>t.id==='deepTask');t.process='In progress';c.syncDirectPlanTask(t);assert.equal(c.state.plans[2].tasks[0].process,'In progress');});
test('server maps direct Plan relation into plan tasks snapshot',()=>{const src=fs.readFileSync(__dirname+'/server.js','utf8');assert.match(src,/planRelationName: todo.planRelation/);assert.match(src,/planRelationName: gorulen.planRelation/);assert.match(src,/tasks: tasks.get\(`plan:\$\{plan.id\}`\)/);assert.match(src,/queryTaskPages\(\[\], '', false\)/);assert.match(src,/if \(body.planId\) properties\[config.planRelation\]/);});
test('editor retains reminders and passes actual plan, not synthetic board as machine',()=>{assert.match(html,/const reminderInitially=/);assert.match(html,/setTaskDateReminder\(savedReminderId/);assert.match(html,/if\(task&&\(taskMachine\|\|task.planId\)\)openTaskEditor/);assert.match(html,/machineId:targetMachine\?\.id\|\|'',planId:task.planId/);});
function serverMapEnv(){const src=fs.readFileSync(__dirname+'/server.js','utf8'),code=src.slice(src.indexOf('function buildTaskMap('),src.indexOf('const rawCache ='));const c=vm.createContext({relationIds:(p,k)=>p.properties?.[k]?.relation?.map(r=>r.id)||[],select:()=>'',taskIsCompleted:()=>false,title:p=>p.name,person:()=>({id:'',name:''}),multiSelect:()=>[],richText:()=>'',dateStart:()=>'',pageUrl:p=>'https://notion.so/'+p.id,serviceLink:()=>''});vm.runInContext(code,c);return c;}
test('server task map includes plan-only tasks from both sources and equipment separately',()=>{const c=serverMapEnv();const source={key:'todo',relationName:'Makina',planRelationName:'Plan',titleNames:['Name'],statusNames:['Proses']};const direct={id:'direct',name:'Task',properties:{Plan:{relation:[{id:'child'}]}}},machine={id:'machineTask',name:'Machine task',properties:{Makina:{relation:[{id:'pump'}]}}};const map=c.buildTaskMap([{source,pages:[direct,machine]},{source:{...source,key:'gorulen'},pages:[{...direct,id:'work'}]}],['pump'],'');assert.equal(map.get('plan:child').length,2);assert.equal(map.get('plan:child')[0].planId,'child');assert.equal(map.get('pump')[0].id,'machineTask');});
test('task with both Plan and Makina relation is not duplicated in direct-plan group',()=>{const c=serverMapEnv();const map=c.buildTaskMap([{source:{key:'todo',relationName:'Makina',planRelationName:'Plan',titleNames:[],statusNames:[]},pages:[{id:'both',properties:{Plan:{relation:[{id:'child'}]},Makina:{relation:[{id:'pump'}]}}}]}],['pump'],'');assert.equal(map.has('plan:child'),false);assert.equal(map.get('pump').length,1);});
