const fs=require('node:fs');const path=require('node:path');
class SharedPomodoroStore{
 constructor(file=''){this.file=file;this.timers=new Map();this.revision=0;if(file)try{const data=JSON.parse(fs.readFileSync(file,'utf8'));for(const t of data.timers||[])if(t.id)this.timers.set(t.id,t);this.revision=Number(data.revision)||0}catch{}}
 get(id){return this.timers.get(id)}
 put(timer){const value={...timer,revision:this.revision=Math.max(Date.now(),this.revision+1)};this.timers.set(value.id,value);if(this.timers.size>300){const oldest=[...this.timers.values()].filter(t=>!t.running).sort((a,b)=>a.revision-b.revision)[0];if(oldest)this.timers.delete(oldest.id)}if(this.file){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';fs.writeFileSync(tmp,JSON.stringify({revision:this.revision,timers:[...this.timers.values()]}));fs.renameSync(tmp,this.file)}return value}
 snapshot(now=Date.now()){return {ok:true,serverNow:now,revision:this.revision,timers:[...this.timers.values()].map(t=>({...t,remainingSeconds:t.running?Math.max(0,Math.ceil((t.endsAt-now)/1000)):t.remainingSeconds}))}}
}
function timerFromTask(task,now=Date.now()){const mode=String(task.pomodoroMode||'').toLowerCase().includes('перерыв')?'break':'work';const duration=Math.max(1,Math.min(mode==='break'?60:180,Number(task.pomodoroDuration)||(mode==='break'?5:25)));const started=Date.parse(task.pomodoroStartedAt),running=Boolean(task.pomodoroRunning&&Number.isFinite(started));return{id:task.id,title:task.title||'Pomodoro',mode,duration,running,status:running?'running':'stopped',startedAt:running?task.pomodoroStartedAt:'',endsAt:running?started+duration*60000:0,remainingSeconds:running?Math.max(0,Math.ceil((started+duration*60000-now)/1000)):duration*60,sessionId:running?task.id+':'+task.pomodoroStartedAt:'',openedAt:0,pomodoroCount:Number(task.pomodoroCount)||0,pomodoroMinutes:Number(task.pomodoroMinutes)||0}}
module.exports={SharedPomodoroStore,timerFromTask};
