/* SSE invalidations + revisioned deltas. No Notion polling per tab. */
(function(root){'use strict';
 function merge(base,packet){if(packet.kind==='full')return packet.data;if(!base)throw Error('Missing delta base');const out={...base,...packet.set};for(const k of packet.unset||[])delete out[k];for(const [k,c] of Object.entries(packet.collections||{})){const map=new Map((base[k]||[]).map(x=>[x.id,x]));for(const id of c.remove||[])map.delete(id);for(const item of c.upsert||[])map.set(item.id,item);out[k]=[...map.values()];}return out;}
 class Client{
 constructor({base='',apply,fetchFn=(...a)=>root.fetch(...a),Source=root.EventSource,scopes=['personal','equipment','management'],delay=150}){Object.assign(this,{base,apply,fetchFn,Source,scopes,delay});this.packets=new Map();this.pending=new Set();this.jobs=new Map();this.retry=5000;this.connected=false;this.stopped=false;this.generation=0;}
 start(){this.stopped=false;if(!this.Source)return;this.connect();}
 connect(){if(this.stopped||this.source)return;const source=this.source=new this.Source(this.base+'/api/events?scopes='+this.scopes.join(','));source.addEventListener('ready',e=>{if(this.source!==source)return;try{const d=JSON.parse(e.data);this.connected=true;this.retry=5000;this.epoch=d.epoch;for(const scope of d.scopes)this.request(scope);this.status('connected');}catch{}});source.addEventListener('change',e=>{if(this.source!==source)return;try{const d=JSON.parse(e.data);this.epoch=d.epoch;this.request(d.scope);}catch{}});source.addEventListener('work-changed',()=>{root.dispatchEvent?.(new Event('adib-work-changed'));});source.addEventListener('warning',()=>this.status('retrying'));source.onerror=()=>{if(this.source!==source)return;source.close();this.source=null;this.connected=false;this.status('reconnecting');const wait=this.retry+Math.random()*1000;this.retry=Math.min(60000,this.retry*2);this.reconnect=setTimeout(()=>this.connect(),wait);};}
 status(value){root.dispatchEvent?.(new CustomEvent('adib-realtime-status',{detail:{status:value}}));}
 request(scope){if(this.stopped||!this.scopes.includes(scope))return;this.pending.add(scope);if(this.timer)return;this.timer=setTimeout(()=>{this.timer=null;for(const s of [...this.pending]){this.pending.delete(s);this.update(s);}},this.delay);}
 async update(scope){const generation=this.generation;if(this.jobs.has(scope)){this.pending.add(scope);return;}const job=(async()=>{try{const prev=this.packets.get(scope);const query=new URLSearchParams({scope,epoch:prev?.epoch||'',revision:String(prev?.revision||0)});const response=await this.fetchFn(this.base+'/api/realtime/state?'+query,{cache:'no-store'});if(!response.ok)throw Error('Realtime HTTP '+response.status);const packet=await response.json();if(this.stopped||generation!==this.generation)return;if(packet.kind==='delta'&&(!prev||packet.epoch!==prev.epoch||packet.baseRevision!==prev.revision)){this.packets.delete(scope);this.pending.add(scope);return;}const data=merge(prev?.data,packet);await this.apply(scope,data);this.packets.set(scope,{epoch:packet.epoch,revision:packet.revision,data});}catch{if(!this.stopped){this.status('retrying');clearTimeout(this.retryUpdate);this.retryUpdate=setTimeout(()=>this.request(scope),5000);}}finally{this.jobs.delete(scope);if(this.pending.has(scope)){this.pending.delete(scope);this.request(scope);}}})();this.jobs.set(scope,job);return job;}
 stop(){this.generation++;this.stopped=true;this.connected=false;this.source?.close();this.source=null;clearTimeout(this.timer);clearTimeout(this.reconnect);clearTimeout(this.retryUpdate);this.pending.clear();}
 }
 root.ADIBRealtime={Client,merge};if(typeof module==='object'&&module.exports)module.exports={Client,merge};
})(typeof window==='object'?window:globalThis);
