const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {SharedPomodoroStore,timerFromTask}=require('./pomodoro-shared');
function env(){let task={id:'test',title:'Test',pomodoroRunning:false,pomodoroCount:0,pomodoroMinutes:0},patches=0;const src=fs.readFileSync(__dirname+'/server.js','utf8'),code=src.slice(src.indexOf('const {SharedPomodoroStore'),src.indexOf('\nasync function aiChat'));
const c=vm.createContext({require:()=>({SharedPomodoroStore,timerFromTask}),process:{env:{}},path:{join:()=>''},__dirname:'',Date,Map,Set,Promise,TASKS_DB:'tasks',TASKS_DS:'ds',cleanId:x=>x,mapPersonalTask:()=>({...task}),pomodoroModeName:(m,d)=>m+':'+d,personalTasksCache:{},queryDatabase:async()=>task.pomodoroRunning?[{}]:[],notion:async(url,o)=>{if(o.method==='PATCH'){patches++;const p=JSON.parse(o.body).properties;if(p['Отчет запущен'])task.pomodoroRunning=p['Отчет запущен'].checkbox;if(p['Начало отчета'])task.pomodoroStartedAt=p['Начало отчета'].date?.start||'';if(p['Pomodoro количество'])task.pomodoroCount=p['Pomodoro количество'].number;if(p['Pomodoro всего минут'])task.pomodoroMinutes=p['Pomodoro всего минут'].number;if(p['Pomodoro текущая длительность'])task.pomodoroDuration=p['Pomodoro текущая длительность'].number;}return {}}});vm.runInContext(code,c);return {c,task,patches:()=>patches,save:b=>c.savePersonalPomodoro({id:'test',...b})};}
test('shared store persists paused state and monotonic revisions',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pomodoro-'));try{const file=path.join(dir,'state.json'),s=new SharedPomodoroStore(file),a=s.put({id:'x',running:false,status:'paused',remainingSeconds:110}),b=s.put({...a,remainingSeconds:109});assert.ok(b.revision>a.revision);assert.equal(new SharedPomodoroStore(file).snapshot().timers[0].remainingSeconds,109)}finally{fs.rmSync(dir,{recursive:true})}});
test('open announces ready window without starting or writing Notion',async()=>{const e=env(),r=await e.save({action:'open'});assert.equal(r.timer.status,'ready');assert.ok(r.timer.openedAt);assert.equal(e.patches(),0);assert.equal(r.timer.running,false)});
test('concurrent device starts keep one start and same session',async()=>{const e=env(),r=await Promise.all([e.save({action:'start',duration:25}),e.save({action:'start',duration:25})]);assert.equal(e.patches(),1);assert.equal(r[0].timer.sessionId,r[1].timer.sessionId);assert.equal(r[1].duplicate,true)});
test('pause/resume keeps exact remaining seconds and full credited duration',async()=>{const e=env(),a=await e.save({action:'start',duration:25,remainingSeconds:100}),b=await e.save({action:'pause',duration:2,sessionId:a.timer.sessionId});assert.ok(b.timer.remainingSeconds<=100);assert.equal(b.timer.status,'paused');const c=await e.save({action:'start',duration:2,remainingSeconds:b.timer.remainingSeconds,sessionId:b.timer.sessionId});assert.equal(c.timer.duration,25);assert.equal(c.timer.remainingSeconds,b.timer.remainingSeconds);await e.save({action:'finish',sessionId:c.timer.sessionId});assert.equal(e.task.pomodoroMinutes,25)});
test('two devices finish once; stale completion cannot stop newer session',async()=>{const e=env(),a=await e.save({action:'start',duration:5});await Promise.all([e.save({action:'finish',sessionId:a.timer.sessionId}),e.save({action:'finish',sessionId:a.timer.sessionId})]);assert.equal(e.task.pomodoroCount,1);await new Promise(r=>setTimeout(r,3));const b=await e.save({action:'start',duration:5});const stale=await e.save({action:'finish',sessionId:a.timer.sessionId});assert.equal(stale.stale,true);assert.equal(stale.timer.running,true);assert.equal(stale.timer.sessionId,b.timer.sessionId)});
test('reset is shared and does not credit statistics',async()=>{const e=env(),a=await e.save({action:'start'});const r=await e.save({action:'reset',sessionId:a.timer.sessionId});assert.equal(r.timer.running,false);assert.equal(r.timer.status,'stopped');assert.equal(e.task.pomodoroCount,0)});
test('restart discovers active Notion timer and adjusts end from timestamp',async()=>{const e=env();e.task.pomodoroRunning=true;e.task.pomodoroDuration=25;e.task.pomodoroStartedAt=new Date().toISOString();const snapshot=await e.c.sharedPomodoroSnapshot();assert.equal(snapshot.timers.length,1);assert.equal(snapshot.timers[0].running,true);assert.ok(snapshot.timers[0].remainingSeconds>1490)});
test('HTTP endpoint and web polling are wired',()=>{const server=fs.readFileSync(__dirname+'/server.js','utf8'),html=fs.readFileSync(__dirname+'/ela-nov-paketleme-dynamic.html','utf8');assert.match(server,/url.pathname === '\/api\/pomodoro-state'/);assert.match(html,/setInterval\(\(\)=>\{if\(!document.hidden\)pollSharedPomodoro\(\)\},5000\)/);assert.match(html,/remotePomodoro\(id,'pause',current\)/)});
test('standalone widget timer shares without a Notion page',async()=>{const e=env(),a=await e.c.savePersonalPomodoro({id:'00000000-0000-4000-8000-000000000001',action:'start',duration:25});assert.equal(a.timer.running,true);assert.equal(e.patches(),0);const b=await e.c.savePersonalPomodoro({id:a.id,action:'pause',sessionId:a.timer.sessionId});assert.equal(b.timer.status,'paused');assert.equal(e.patches(),0)});
