const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {SharedPomodoroStore,timerFromTask}=require('./pomodoro-shared');
function env(){let task={id:'test',title:'Test',pomodoroRunning:false,pomodoroCount:0,pomodoroMinutes:0},patches=0;const src=fs.readFileSync(__dirname+'/server.js','utf8'),code=src.slice(src.indexOf('const {SharedPomodoroStore'),src.indexOf('\nasync function aiChat'));
const c=vm.createContext({require:()=>({SharedPomodoroStore,timerFromTask}),process:{env:{}},path:{join:()=>''},__dirname:'',Date,Map,Set,Promise,TASKS_DB:'tasks',TASKS_DS:'ds',cleanId:x=>x,mapPersonalTask:()=>({...task}),pomodoroModeName:(m,d)=>m+':'+d,personalTasksCache:{},queryDatabase:async()=>task.pomodoroRunning?[{}]:[],notion:async(url,o)=>{if(o.method==='PATCH'){patches++;const p=JSON.parse(o.body).properties;if(p['Pomodoro режим'])task.pomodoroMode=p['Pomodoro режим'].select.name;if(p['Отчет запущен'])task.pomodoroRunning=p['Отчет запущен'].checkbox;if(p['Начало отчета'])task.pomodoroStartedAt=p['Начало отчета'].date?.start||'';if(p['Pomodoro количество'])task.pomodoroCount=p['Pomodoro количество'].number;if(p['Pomodoro всего минут'])task.pomodoroMinutes=p['Pomodoro всего минут'].number;if(p['Pomodoro текущая длительность'])task.pomodoroDuration=p['Pomodoro текущая длительность'].number;}return {}}});vm.runInContext(code,c);return {c,task,patches:()=>patches,save:b=>c.savePersonalPomodoro({id:'test',...b})};}
test('shared store persists paused state and monotonic revisions',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pomodoro-'));try{const file=path.join(dir,'state.json'),s=new SharedPomodoroStore(file),a=s.put({id:'x',running:false,status:'paused',remainingSeconds:110}),b=s.put({...a,remainingSeconds:109});assert.ok(b.revision>a.revision);assert.equal(new SharedPomodoroStore(file).snapshot().timers[0].remainingSeconds,109)}finally{fs.rmSync(dir,{recursive:true})}});
test('open announces ready window without starting or writing Notion',async()=>{const e=env(),r=await e.save({action:'open'});assert.equal(r.timer.status,'ready');assert.ok(r.timer.openedAt);assert.equal(e.patches(),0);assert.equal(r.timer.running,false)});
test('concurrent device starts keep one start and same session',async()=>{const e=env(),r=await Promise.all([e.save({action:'start',duration:25}),e.save({action:'start',duration:25})]);assert.equal(e.patches(),1);assert.equal(r[0].timer.sessionId,r[1].timer.sessionId);assert.equal(r[1].duplicate,true)});
test('pause/resume keeps exact remaining seconds and full credited duration',async()=>{const e=env(),a=await e.save({action:'start',duration:25,remainingSeconds:100}),b=await e.save({action:'pause',duration:2,sessionId:a.timer.sessionId});assert.ok(b.timer.remainingSeconds<=100);assert.equal(b.timer.status,'paused');const c=await e.save({action:'start',duration:2,remainingSeconds:b.timer.remainingSeconds,sessionId:b.timer.sessionId});assert.equal(c.timer.duration,25);assert.equal(c.timer.remainingSeconds,b.timer.remainingSeconds);await e.save({action:'finish',sessionId:c.timer.sessionId});assert.equal(e.task.pomodoroMinutes,25)});
test('two devices finish once; stale completion cannot stop newer session',async()=>{const e=env(),a=await e.save({action:'start',duration:5});await Promise.all([e.save({action:'finish',sessionId:a.timer.sessionId}),e.save({action:'finish',sessionId:a.timer.sessionId})]);assert.equal(e.task.pomodoroCount,1);await new Promise(r=>setTimeout(r,3));const b=await e.save({action:'start',duration:5});const stale=await e.save({action:'finish',sessionId:a.timer.sessionId});assert.equal(stale.stale,true);assert.equal(stale.timer.running,true);assert.equal(stale.timer.sessionId,b.timer.sessionId)});
test('reset is shared and does not credit statistics',async()=>{const e=env(),a=await e.save({action:'start'});const r=await e.save({action:'reset',sessionId:a.timer.sessionId});assert.equal(r.timer.running,false);assert.equal(r.timer.status,'stopped');assert.equal(e.task.pomodoroCount,0)});
test('restart discovers active Notion timer and adjusts end from timestamp',async()=>{const e=env();e.task.pomodoroRunning=true;e.task.pomodoroDuration=25;e.task.pomodoroStartedAt=new Date().toISOString();const snapshot=await e.c.sharedPomodoroSnapshot();assert.equal(snapshot.timers.length,1);assert.equal(snapshot.timers[0].running,true);assert.ok(snapshot.timers[0].remainingSeconds>1490)});
test('HTTP endpoint and web polling are wired',()=>{const server=fs.readFileSync(__dirname+'/server.js','utf8'),html=fs.readFileSync(__dirname+'/ela-nov-paketleme-dynamic.html','utf8');assert.match(server,/url.pathname === '\/api\/pomodoro-state'/);assert.match(html,/setInterval\(\(\)=>\{if\(!document.hidden\)pollSharedPomodoro\(\)\},5000\)/);assert.match(html,/remotePomodoro\(id,'pause',current\)/)});
test('standalone widget timer shares without a Notion page',async()=>{const e=env(),a=await e.c.savePersonalPomodoro({id:'00000000-0000-4000-8000-000000000001',action:'start',duration:25});assert.equal(a.timer.running,true);assert.equal(e.patches(),0);const b=await e.c.savePersonalPomodoro({id:a.id,action:'pause',sessionId:a.timer.sessionId});assert.equal(b.timer.status,'paused');assert.equal(e.patches(),0)});

test('restart after resume retains full 25 minute credit and exact remaining',async()=>{const e=env(),a=await e.save({action:'start',duration:25,remainingSeconds:769});await e.save({action:'pause',sessionId:a.timer.sessionId});const b=await e.save({action:'start',duration:13,remainingSeconds:769,sessionId:a.timer.sessionId});assert.equal(e.task.pomodoroDuration,25);const fresh=env();Object.assign(fresh.task,e.task);const r=await fresh.c.sharedPomodoroSnapshot();assert.equal(r.timers[0].plannedDuration,25);assert.ok(Math.abs(r.timers[0].endsAt-b.timer.endsAt)<1000);await fresh.save({action:'finish',sessionId:r.timers[0].sessionId});assert.equal(fresh.task.pomodoroMinutes,25)});
test('legacy fractional duration recovers planned 25 without extending end',async()=>{const e=env();Object.assign(e.task,{pomodoroRunning:true,pomodoroDuration:12.816666666666666,pomodoroMode:'Работа — 25 мин',pomodoroStartedAt:new Date().toISOString()});const s=await e.c.sharedPomodoroSnapshot(),t=s.timers[0];assert.equal(t.duration,25);assert.ok(t.remainingSeconds<=770&&t.remainingSeconds>=768);const done=await e.save({action:'finish',sessionId:t.sessionId});assert.equal(done.timer.status,'completed');assert.equal(done.timer.creditedMinutes,25);assert.equal(e.task.pomodoroMinutes,25)});
test('early finish credits integer worked minutes, not full planned',async()=>{const e=env(),a=await e.save({action:'start',duration:25,remainingSeconds:730}),r=await e.save({action:'finish',early:true,sessionId:a.timer.sessionId});assert.equal(r.timer.completionReason,'early');assert.equal(r.timer.creditedMinutes,13);assert.equal(e.task.pomodoroMinutes,13);assert.equal(e.task.pomodoroCount,1);await e.save({action:'finish',early:true,sessionId:a.timer.sessionId});assert.equal(e.task.pomodoroCount,1)});
test('paused early finish excludes idle time and is allowed once',async()=>{const e=env(),a=await e.save({action:'start',duration:25,remainingSeconds:900});await e.save({action:'pause',sessionId:a.timer.sessionId});vm.runInContext("sharedPomodoro.get('test').startedAt=new Date(Date.now()-3600000).toISOString()",e.c);const r=await e.save({action:'finish',early:true,sessionId:a.timer.sessionId});assert.equal(r.timer.creditedMinutes,10);assert.equal(e.task.pomodoroMinutes,10);assert.equal(r.timer.status,'completed')});
test('integer custom duration retained and new statistic writes integer',async()=>{const e=env();e.task.pomodoroMinutes=12.816666666666666;const a=await e.save({action:'start',duration:40});assert.equal(a.timer.duration,40);await e.save({action:'finish',sessionId:a.timer.sessionId});assert.equal(e.task.pomodoroMinutes,53)});

test('late pause cannot revive a timer already stopped on another device',async()=>{const e=env(),a=await e.save({action:'start',duration:25});await e.save({action:'finish',early:true,sessionId:a.timer.sessionId});const before=e.patches(),r=await e.save({action:'pause',sessionId:a.timer.sessionId});assert.equal(r.timer.status,'completed');assert.equal(r.duplicate,true);assert.equal(e.patches(),before)});
test('repeated pause is idempotent and cannot pause an idle task',async()=>{const e=env(),idle=await e.save({action:'pause'});assert.notEqual(idle.timer.status,'paused');assert.equal(e.patches(),0);const a=await e.save({action:'start'});await e.save({action:'pause',sessionId:a.timer.sessionId});const before=e.patches(),r=await e.save({action:'pause',sessionId:a.timer.sessionId});assert.equal(r.timer.status,'paused');assert.equal(r.duplicate,true);assert.equal(e.patches(),before)});
