const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const html=fs.readFileSync(__dirname+'/ela-nov-paketleme-dynamic.html','utf8');
function env(status='idle',mode='work'){const timer={mode,running:status==='running',status,remainingSeconds:769,workMinutes:25,breakMinutes:5,sessionId:'session',endsAt:status==='running'?Date.now()+769000:null},calls=[];const c=vm.createContext({personalPomodoroData:{stats:{},timers:{x:timer}},window:{},escapeHtml:s=>String(s).replaceAll('"','&quot;').replaceAll('<','&lt;'),savePomodoroData:()=>{},Date,document:{querySelectorAll:()=>[],addEventListener:()=>{}},pomodoroTaskById:id=>id==='x'?{id}:null,remotePomodoro:async(id,action,state,extra)=>{calls.push({id,action,state,extra});},ensurePomodoroInterval:()=>{},pomodoroUpdateModal:()=>{}});vm.runInContext(html.slice(html.indexOf('  function personalTaskPomodoroRemaining('),html.indexOf('  const sharedPomodoroTasks=')),c);vm.runInContext(html.slice(html.indexOf('  function pomodoroFormat('),html.indexOf('  function renderPomodoroOverlay(')),c);return{c,timer,calls}}
test('start from idle always starts fresh work, not leftover break',async()=>{const e=env('completed','break');assert.equal(await e.c.taskPomodoroListAction('x','start'),true);const r=e.calls[0];assert.equal(r.action,'start');assert.equal(r.state.mode,'work');assert.equal(r.state.remainingSeconds,1500);assert.equal(r.state.sessionId,'');assert.equal(e.timer.mode,'break')});
test('resume preserves remaining time, mode and session',async()=>{const e=env('paused');await e.c.taskPomodoroListAction('x','start');const r=e.calls[0];assert.equal(r.state.remainingSeconds,769);assert.equal(r.state.sessionId,'session');assert.equal(r.state.mode,'work')});
test('pause uses remaining countdown without speculative local stop',async()=>{const e=env('running');await e.c.taskPomodoroListAction('x','pause');assert.equal(e.calls[0].action,'pause');assert.ok(e.calls[0].state.remainingSeconds<=769);assert.equal(e.timer.running,true)});
test('stop requests early credit with active session; paused break stops as break',async()=>{const e=env('paused');await e.c.taskPomodoroListAction('x','stop');assert.equal(e.calls[0].action,'finish');assert.equal(e.calls[0].extra.early,true);assert.equal(e.calls[0].state.sessionId,'session');assert.equal(e.calls[0].state.remainingSeconds,769);const b=env('paused','break');await b.c.taskPomodoroListAction('x','stop');assert.equal(b.calls[0].action,'break-finish')});
test('invalid/inapplicable actions never send writes',async()=>{const e=env();for(const a of ['pause','stop','reset','delete'])assert.equal(await e.c.taskPomodoroListAction('x',a),false);assert.equal(await e.c.taskPomodoroListAction('unknown','start'),false);assert.equal(e.calls.length,0);const r=env('running');assert.equal(await r.c.taskPomodoroListAction('x','start'),false)});
test('double click during save sends one action',async()=>{const e=env();let done;e.c.remotePomodoro=()=>new Promise(resolve=>done=resolve);const a=e.c.taskPomodoroListAction('x','start');assert.equal(await e.c.taskPomodoroListAction('x','start'),false);done({});assert.equal(await a,true)});
test('network failure keeps timer state and releases busy guard for retry',async()=>{const e=env('running');e.c.remotePomodoro=async()=>{throw Error('offline')};assert.equal(await e.c.taskPomodoroListAction('x','pause'),false);assert.equal(e.timer.running,true);assert.equal(vm.runInContext('taskPomodoroBusy.size',e.c),0);assert.match(vm.runInContext("taskPomodoroErrors.get('x')",e.c),/Не удалось сохранить/);e.c.remotePomodoro=async()=>({});assert.equal(await e.c.taskPomodoroListAction('x','pause'),true)});
test('start/pause/stop controls and list scopes are wired; no nested desktop buttons',()=>{assert.match(html,/personalListRow=task=>[^\n]+personalTaskPomodoroIndicator\(task,true\)/);assert.match(html,/function taskBoardChecklistRow[^\n]+personalPomodoroIndicatorForTask\?\.\(task,true\)/);assert.match(html,/row=document.createElement\('div'\);row.className='personal-desktop-task-row'/);assert.match(html,/event.stopImmediatePropagation\(\);if\(!button.disabled\)/);assert.match(html,/min-height:44px!important/);assert.match(html,/display&&display.innerHTML!==markup/)});
