const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const html=fs.readFileSync(__dirname+'/ela-nov-paketleme-dynamic.html','utf8');
function env(){const c=vm.createContext({personalPomodoroData:{stats:{},timers:{}},window:{},escapeHtml:s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;'),savePomodoroData:()=>{},Date,document:{querySelectorAll:()=>[],addEventListener:()=>{}}});vm.runInContext(html.slice(html.indexOf('  function personalTaskPomodoroRemaining('),html.indexOf('  const sharedPomodoroTasks=')),c);vm.runInContext(html.slice(html.indexOf('  function pomodoroFormat('),html.indexOf('  function renderPomodoroOverlay(')),c);return c}
test('zero stats are always visible; ready is not paused',()=>{const c=env();c.personalPomodoroData.timers.x={running:false,status:'ready',remainingSeconds:1500};const m=c.personalTaskPomodoroIndicator({id:'x'});assert.match(m,/🍅 0 · 0 мин/);assert.doesNotMatch(m,/на паузе|идёт/)});
test('completed stats use integer minutes and count without changing stored values',()=>{const c=env(),task={id:'x',pomodoroCount:3,pomodoroMinutes:74.8};assert.match(c.personalTaskPomodoroIndicator(task),/🍅 3 · 75 мин/);assert.equal(task.pomodoroMinutes,74.8)});
test('active timer counts down; totals remain completed credit only',()=>{const c=env();c.personalPomodoroData.stats.x={count:2,minutes:50};c.personalPomodoroData.timers.x={running:true,status:'running',mode:'work',workMinutes:25,endsAt:Date.now()+65000};const m=c.personalTaskPomodoroIndicator({id:'x'});assert.match(m,/🍅 2 · 50 мин/);assert.match(m,/Помидор идёт/);assert.match(m,/01:05/)});
test('paused countdown does not decrease with elapsed wall time',()=>{const c=env();c.personalPomodoroData.timers.x={running:false,status:'paused',mode:'work',workMinutes:25,remainingSeconds:769,endsAt:null};const a=c.personalTaskPomodoroIndicator({id:'x'});assert.match(a,/Помидор на паузе/);assert.match(a,/12:49/);assert.equal(a,c.personalTaskPomodoroIndicator({id:'x'}))});
test('break timer explicitly labeled; completed/reset has no active badge',()=>{const c=env();c.personalPomodoroData.timers.x={running:false,status:'paused',mode:'break',breakMinutes:5,remainingSeconds:90};assert.match(c.personalTaskPomodoroIndicator({id:'x'}),/Перерыв на паузе/);c.personalPomodoroData.timers.x.status='completed';assert.doesNotMatch(c.personalTaskPomodoroIndicator({id:'x'}),/на паузе|идёт/)});
test('markup escapes task id',()=>{const c=env();assert.ok(!c.personalTaskPomodoroIndicator({id:'\"><script>'}).includes('<script>'))});
test('visible summaries update in place without removing idle rows',()=>{const c=env();let task={id:'x',pomodoroCount:1,pomodoroMinutes:25},display={innerHTML:''},el={dataset:{pomodoroIndicator:'x'},querySelector:sel=>sel==='.task-pomodoro-display'?display:null,querySelectorAll:()=>[],setAttribute:()=>{}};c.pomodoroTaskById=()=>task;c.document.querySelectorAll=()=>[el];c.updatePersonalPomodoroIndicators();assert.match(display.innerHTML,/1 · 25 мин/);task.pomodoroCount=2;task.pomodoroMinutes=50;c.updatePersonalPomodoroIndicators();assert.match(display.innerHTML,/2 · 50 мин/)});
test('equipment checklist and desktop container task list include shared indicator',()=>{assert.match(html,/function taskBoardChecklistRow[^\n]+window.personalPomodoroIndicatorForTask/);assert.match(html,/row.className='personal-desktop-task-row'[^\n]+personalTaskPomodoroIndicator/);assert.match(html,/function taskBoardListRow[^\n]+window.personalPomodoroIndicatorForTask/)});
