(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.ADIBTaskHistory=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const DAYS=7,WINDOW=DAYS*86400000;let clock=()=>typeof globalThis!=='undefined'&&globalThis.ADIBClock?.now?globalThis.ADIBClock.now():Date.now();function setClock(fn){clock=fn;}function now(){return clock();}
function done(t){if(!t)return false;if(t.completed===true)return true;return /^(done|complete|completed|is goruldu|tamamlandi|bitdi|bitib|выполнено|выполнена)$/i.test(String(t.process||t.status||'').trim());}
function visible(t,now=clock()){if(!t||t.archived||t.in_trash||t.deleted)return false;if(!done(t)||!Number.isFinite(now))return true;const at=Date.parse(t.completedAt||'');return Number.isFinite(at)&&at>=now-WINDOW&&at<=now+60000;}
function counts(tasks,now=clock()){const c={open:0,done:0,total:0,todo:0,gorulen:0,urgent:0};const seen=new Set();for(const t of tasks||[]){if(!visible(t,now)||seen.has(t.id))continue;seen.add(t.id);c.total++;c[done(t)?'done':'open']++;c[t.sourceKey==='gorulen'?'gorulen':'todo']++;if(!done(t)&&(t.urgent||String(t.priority||'').trim()==='!!!'))c.urgent++;}return c;}
function color(tasks,fallback='#dcecf8',now=clock()){const c=counts(tasks,now);return c.open&&c.done?'#ffe699':c.open?'#f4b183':c.done?'#a9d18e':fallback;}
function CompletionHistory(file){this.file=file;this.rows={};if(file){const fs=require('node:fs');try{this.rows=JSON.parse(fs.readFileSync(file,'utf8'));}catch{}}}
CompletionHistory.prototype.schedule=function(){if(this.pending)return;this.pending=true;Promise.resolve().then(()=>{this.pending=false;try{this.save();}catch(e){this.error=String(e.message||e);}});};
CompletionHistory.prototype.save=function(){if(!this.file)return;const fs=require('node:fs'),path=require('node:path');fs.mkdirSync(path.dirname(this.file),{recursive:true});fs.writeFileSync(this.file+'.tmp',JSON.stringify(this.rows));fs.renameSync(this.file+'.tmp',this.file);};
CompletionHistory.prototype.enrich=function(task,page={},meta={}){const prior=this.rows[task.id];if(!done(task)){if(prior?.done||meta.completedAt){const next={done:false,ignoredMetaAt:meta.completedAt||prior?.ignoredMetaAt||prior?.completedAt||''};if(JSON.stringify(next)!==JSON.stringify(prior)){this.rows[task.id]=next;this.schedule();}}return {...task,completed:false,completedAt:null};}const properties=page.properties||{};let explicit='';for(const name of ['Completed at','Дата выполнения','Дата завершения','Tamamlanma tarixi']){const value=properties[name]?.date?.start;if(Number.isFinite(Date.parse(value||''))){explicit=value;break;}}const metaAt=meta.completedAt!==prior?.ignoredMetaAt&&Number.isFinite(Date.parse(meta.completedAt||''))?meta.completedAt:'';const exact=metaAt||explicit;const fallback=Number.isFinite(Date.parse(page.last_edited_time||task.updatedAt||''))?page.last_edited_time||task.updatedAt:'';const at=exact||(prior?.done?prior.completedAt:'')||fallback;const source=exact?(metaAt?meta.completionDateSource||'recorded':'recorded'):prior?.done?prior.source:'last-edited-estimate';const next={done:true,completedAt:at,source,...(prior?.ignoredMetaAt&&!metaAt?{ignoredMetaAt:prior.ignoredMetaAt}:{})};if(JSON.stringify(next)!==JSON.stringify(prior)){this.rows[task.id]=next;this.schedule();}return {...task,completed:true,completedAt:at||null,completionDateSource:source};};
function snapshot(data,now=clock()){const out={...data};if(Array.isArray(data.tasks))out.tasks=data.tasks.filter(t=>visible(t,now));for(const key of ['plans','equipment'])if(Array.isArray(data[key]))out[key]=data[key].map(o=>({...o,tasks:(o.tasks||[]).filter(t=>visible(t,now)),...(key==='equipment'?{taskCounts:counts(o.tasks,now)}:{})}));return out;}
return {DAYS,WINDOW,now,setClock,done,visible,counts,color,snapshot,CompletionHistory};});
