(function(root){'use strict';
function install(list,{task={},personal=false,isNew=false,onAddChild,onCompleteChild,children=[],onOpenChild,onOpenParent,parentTitle=''}={}){
 if(isNew)return null;const editor=list.querySelector('.task-editor');if(!editor)return null;
 const title=editor.querySelector(personal?'#personalEditTitle':'#taskTitle');const host=document.createElement('section');host.className='adib-task-detail';host.innerHTML='<header class="adib-task-detail-header"><div class="adib-task-title-group"><strong></strong><small></small></div><div class="adib-task-header-tools"></div></header><nav class="adib-task-tabs" role="tablist" aria-label="Разделы задачи"></nav><div class="adib-task-panes"></div><footer class="adib-task-footer"></footer>';
 const heading=host.querySelector('header strong'),panel=list.closest('.modal,.kanban-task-editor-panel,.personal-kanban-editor-panel'),outerHeading=panel?.querySelector('.modal-head h2,.kanban-task-editor-head strong,.personal-kanban-editor-head strong');if(outerHeading)host.querySelector('header').classList.add('unified-heading');const update=()=>{heading.textContent=title?.value||task.title||'Без названия';if(outerHeading)outerHeading.textContent=heading.textContent;};update();title?.addEventListener('input',update);host.querySelector('header small').textContent=personal?'Мои задачи':(task.sourceKey==='gorulen'?'Gorulen isler':'ToDo');
 if(task.parentId&&onOpenParent){const back=document.createElement('button');back.type='button';back.className='adib-task-parent-link';back.dataset.taskOpenParent=String(task.parentId);back.textContent='← К родительской задаче';back.title=parentTitle?'Родитель: '+parentTitle:'Открыть родительскую задачу';back.onclick=()=>navigate(onOpenParent);host.querySelector('.adib-task-title-group').append(back)}
 const keys=['chat','task','description','subtasks'],labels=['Чат','Задача','Описание','Подзадачи'],panes={};keys.forEach((key,i)=>{const tab=document.createElement('button');tab.type='button';tab.setAttribute('role','tab');tab.textContent=labels[i];tab.dataset.taskTab=key;const pane=document.createElement('section');pane.setAttribute('role','tabpanel');pane.dataset.taskPane=key;pane.tabIndex=0;tab.id='task-tab-'+key+'-'+String(task.id).replace(/[^\w-]/g,'');pane.id=tab.id+'-pane';tab.setAttribute('aria-controls',pane.id);pane.setAttribute('aria-labelledby',tab.id);host.querySelector('nav').append(tab);host.querySelector('.adib-task-panes').append(pane);panes[key]=pane;tab.onclick=()=>key==='chat'?root.openCommentChat?.(task):select(key)});
 const footer=host.querySelector('footer'),hiddenControls=document.createElement('div');hiddenControls.className='adib-task-hidden-controls';hiddenControls.hidden=true;host.append(hiddenControls);for(const item of [...editor.children]){if(item.matches('#personalEditorBoard,#personalEditorBack')){item.hidden=true;item.setAttribute('aria-hidden','true');hiddenControls.append(item)}else if(item.matches('a')&&item.textContent.includes('Открыть в Notion')){item.className='adib-task-notion-link';item.textContent='↗ Notion';item.title='Открыть задачу в Notion';item.setAttribute('aria-label','Открыть задачу в Notion');item.rel='noopener noreferrer';host.querySelector('.adib-task-header-tools').append(item)}else if(item.matches('.editor-actions,.error'))footer.append(item);else if(item.matches('.personal-page-content-field')||item.querySelector('#taskDoneWork'))panes.description.append(item);else if(item.matches('.personal-task-subtask-properties'))panes.subtasks.append(item);else if(item.matches('.comments-section'))panes.chat.append(item);else panes.task.append(item)}
 const childCount=children.length,subtab=host.querySelector('[data-task-tab="subtasks"]');subtab.textContent=childCount?'Подзадачи · '+childCount:'Подзадачи';subtab.setAttribute('aria-label',childCount?'Подзадачи: '+childCount:'Подзадачи: нет');editor.append(host);const subhead=document.createElement('h3');subhead.textContent='Подзадачи';panes.subtasks.prepend(subhead);
 let dirty=false;list.addEventListener('adib-autosaved',()=>dirty=false);list.addEventListener('adib-autostored',()=>dirty=false);[panes.task,panes.description].forEach(p=>{p.addEventListener('input',()=>dirty=true);p.addEventListener('change',()=>dirty=true)});
 function navigate(callback){if(!callback)return;if(editor.querySelector('#personalEditorSave:disabled,#saveTask:disabled')){root.alert('Дождитесь завершения сохранения задачи.');return}const draft=Boolean(panes.chat.querySelector('textarea')?.value.trim()||panes.chat.querySelector('.adib-image-picker .adib-image-thumbs img'));if((dirty||draft)&&!root.confirm('Есть несохранённые изменения или черновик комментария. Перейти без сохранения?'))return;Promise.resolve().then(callback).catch(e=>root.alert('Не удалось открыть задачу. '+e.message))}
 const legacyRows=[...panes.subtasks.querySelectorAll('[data-task-open-child]')];
 if(legacyRows.length){for(const row of legacyRows){const child=children.find(c=>String(c.id)===row.dataset.taskOpenChild)||{id:row.dataset.taskOpenChild};row.onclick=()=>navigate(()=>onOpenChild?.(child));}}
 else for(const child of children){const row=document.createElement('button');row.type='button';row.className='adib-task-link';row.dataset.taskOpenChild=String(child.id);row.textContent=child.title;row.onclick=()=>navigate(()=>onOpenChild?.(child));panes.subtasks.append(row)}
 if(onAddChild){const add=document.createElement('button');add.type='button';add.dataset.taskAddSubtask='';add.className='adib-task-link';add.textContent='+ Добавить подзадачу';add.onclick=()=>{if(panes.chat.querySelector('textarea')?.value.trim()||panes.chat.querySelector('.adib-image-picker .adib-image-thumbs img')){root.alert('Отправьте или очистите черновик комментария перед созданием подзадачи.');return}if(dirty){root.alert('Сначала сохраните изменения задачи, затем добавьте подзадачу.');return}onAddChild()};panes.subtasks.append(add)}else{const note=document.createElement('p');note.className='muted';note.textContent='В этой базе не настроена связь подзадач.';panes.subtasks.append(note)}
 if(onCompleteChild)for(const row of [...panes.subtasks.querySelectorAll('[data-task-open-child]')]){const child=children.find(t=>String(t.id)===row.dataset.taskOpenChild)||{id:row.dataset.taskOpenChild,title:row.querySelector('.personal-task-subtask-property-title')?.textContent||row.textContent.trim(),completed:row.dataset.completed==='true'};const wrap=document.createElement('div');wrap.className='adib-subtask-row';row.before(wrap);wrap.append(row);const check=document.createElement('button');check.type='button';check.className='adib-subtask-check';check.dataset.completeChild=child.id;check.setAttribute('role','checkbox');function update(){check.setAttribute('aria-checked',String(!!child.completed));check.setAttribute('aria-label',(child.completed?'Вернуть в работу: ':'Завершить подзадачу: ')+child.title);check.textContent=child.completed?'✓':'';wrap.classList.toggle('completed',!!child.completed);const status=row.querySelector('small');if(status)status.textContent=child.completed?'Выполнено':child.status||'Not started'}update();wrap.prepend(check);check.onclick=async e=>{e.stopPropagation();if(check.disabled)return;check.disabled=true;try{const updated=await onCompleteChild(child);if(updated)Object.assign(child,updated);update()}catch(error){root.alert(error.message)}finally{check.disabled=false}}}
 const checklist=document.createElement('h3');checklist.textContent='Чек-листы';const note=document.createElement('p');note.className='muted';note.textContent='Пункты проверки и заметки находятся в описании задачи.';const desc=document.createElement('button');desc.type='button';desc.className='adib-task-link';desc.textContent='Открыть описание';desc.onclick=()=>select('description');panes.subtasks.append(checklist,note,desc);
 function select(key){if(key==='chat'&&root.openCommentChat){root.openCommentChat(task);return}list.classList.toggle('adib-task-chat-active',key==='chat');keys.forEach(k=>{panes[k].hidden=k!==key;const tab=host.querySelector('[data-task-tab="'+k+'"]');tab.setAttribute('aria-selected',String(k===key));tab.tabIndex=k===key?0:-1})}
 host.querySelector('nav').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=keys.indexOf(document.activeElement?.dataset.taskTab);i=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;select(keys[i]);host.querySelector('[data-task-tab="'+keys[i]+'"]').focus()});select('task');return {panes,select};
}
root.ADIBTaskTabs={install};
})(window);
