/* Shared task presentation. Data writes remain in the existing view handlers. */
(function(root){'use strict';let sequence=0;
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={'Not started':'Başlanmayıb','Not started / Todo':'Başlanmayıb','Todo':'Başlanmayıb','In progress':'İcra olunur','Done':'Tamamlanıb','Waiting':'Gözləyir','My Day':'Günüm','Delegate':'Həvalə edilib','Is gedir':'İcra olunur','Is goruldu':'Tamamlanıb'};
const checkSvg=done=>'<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="'+(done?'currentColor':'none')+'" stroke="currentColor" stroke-width="1.6"/>'+(done?'<path d="m7 12 3.2 3.2L17 8.5" fill="none" stroke="var(--adib-check-ink,#fff)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>':'')+'</svg>';
const moreSvg='<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>';
const clockSvg='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="13" r="8"/><path d="M9 2h6M12 5V2m5 4 2-2m-7 5v4l3 2"/></svg>';
function chips(items){return items.filter(Boolean).map(item=>{const o=typeof item==='object'?item:{text:item};if(!o.text)return '';return '<span class="adib-card-chip '+(o.kind||'')+((labels[o.text]||o.text)==='Tamamlanıb'?' complete':'')+'">'+escape(labels[o.text]||o.text)+'</span>'}).join('')}
function content(o){const id='adib-card-actions-'+(++sequence),title=escape(o.title||'Adsız');return '<button type="button" class="adib-task-check '+(o.checkClass||'')+'" role="checkbox" aria-checked="'+!!o.done+'" aria-label="'+(o.done?'İşə qayıdın':'Tamamlandı')+'" '+(o.checkAttrs||'')+'>'+checkSvg(o.done)+'</button><div class="adib-card-content '+(o.contentClass||'')+'">'+(o.titleAttrs?'<button type="button" class="adib-card-title" data-card-primary '+o.titleAttrs+'>'+title+'</button>':'<strong class="adib-card-title">'+title+'</strong>')+(o.meta?'<div class="adib-card-meta">'+escape(o.meta)+'</div>':'')+(o.chips?.length?'<div class="adib-card-chips">'+chips(o.chips)+'</div>':'')+(o.timer?'<div class="adib-card-timer">'+o.timer+'</div>':'')+(o.extra||'')+'</div><button type="button" class="adib-card-more" data-card-menu="'+id+'" aria-controls="'+id+'" aria-expanded="false" aria-label="Tapşırıq hərəkətləri">'+moreSvg+'</button><div id="'+id+'" class="adib-card-menu" popover="auto" aria-label="Tapşırıq hərəkətləri"><button type="button" data-card-open-proxy>Xüsusiyyətləri açın</button>'+(o.menu||'')+'</div>'}
function countLabel(n,one,few,many){const v=Math.abs(Number(n)||0)%100;return v>=11&&v<=14?many:v%10===1?one:v%10>=2&&v%10<=4?few:many}
function pomodoroLabel(n){return countLabel(n,'pomodoro','pomodoro','pomodoro')}
function subtaskLabel(n){return countLabel(n,'alt tapşırıq','alt tapşırıqlar','alt tapşırıqlar')}
function totals(count,minutes){return '<span class="adib-card-totals">'+clockSvg+escape(count)+' '+pomodoroLabel(count)+' · '+escape(Math.round(minutes))+' dəq</span>'}
function dialog(subtitle){document.querySelectorAll('.adib-unified-filter').forEach(e=>{e.close();e.remove()});const d=document.createElement('dialog');d.className='adib-home-popover adib-unified-filter';d.id='adibFilterDialog';d.setAttribute('aria-label','Tapşırıq filtri');d.innerHTML='<header class="adib-filter-head"><div><h2>Tapşırıq filtri</h2><small>'+escape(subtitle)+'</small></div><button type="button" class="adib-filter-close" aria-label="Filtri bağlayın">×</button></header><div class="adib-filter-fields"></div><footer class="adib-filter-foot"></footer>';d.querySelector('.adib-filter-close').onclick=()=>{d.close();d.remove()};d.addEventListener('cancel',()=>d.remove());document.body.append(d);return {dialog:d,fields:d.querySelector('.adib-filter-fields'),footer:d.querySelector('.adib-filter-foot'),close:()=>{d.close();d.remove()}}}
function closeMenus(){document.querySelectorAll('.adib-card-menu:popover-open').forEach(e=>e.hidePopover())}
document.addEventListener('click',event=>{const b=event.target.closest?.('[data-card-menu]');if(b){event.preventDefault();event.stopImmediatePropagation();const menu=document.getElementById(b.dataset.cardMenu);if(!menu)return;if(menu.matches(':popover-open')){menu.hidePopover();return}menu.showPopover();const r=b.getBoundingClientRect(),side=parseFloat(getComputedStyle(document.body).getPropertyValue('--adib-side-width'))||0;menu.style.maxWidth=Math.max(180,innerWidth-side-16)+'px';const w=menu.offsetWidth,h=menu.offsetHeight;menu.style.left=Math.max(side+8,Math.min(innerWidth-w-8,r.right-w))+'px';menu.style.top=Math.max(8,Math.min(innerHeight-h-8,r.bottom+6))+'px';return}const proxy=event.target.closest?.('[data-card-open-proxy]');if(proxy){event.preventDefault();event.stopImmediatePropagation();const card=proxy.closest('.adib-task-card'),primary=card?.querySelector('[data-card-primary]');closeMenus();primary?.click();return}if(event.target.closest?.('.adib-card-menu button'))closeMenus()},true);
document.addEventListener('toggle',event=>{const m=event.target;if(m?.classList?.contains('adib-card-menu'))document.querySelector('[data-card-menu="'+m.id+'"]')?.setAttribute('aria-expanded',String(event.newState==='open'))},true);
root.addEventListener('resize',closeMenus);root.ADIBTaskCards={escape,checkSvg,clockSvg,content,totals,pomodoroLabel,subtaskLabel,chips,dialog,closeMenus,label:value=>labels[value]||root.ADIBAz?.label(value)||value};
})(window);
