'use strict';
const crypto=require('node:crypto');
const FIELDS=['Foto evvel','Foto sonra'];
const error=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode});
const key=id=>String(id||'').replace(/-/g,'').toLowerCase();
const valid=id=>/^[a-f0-9]{32}$/.test(key(id));
const safe=url=>{try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
const version=files=>crypto.createHash('sha256').update(JSON.stringify(files.map(f=>[f.name,f.type,(f.file?.url||f.external?.url||'').split('?')[0]]))).digest('hex');
function create({notion,sources}){
 const locks=new Map(),metadata=new Map(),flights=new Map();
 async function locked(id,fn){const prior=locks.get(key(id))||Promise.resolve();const job=prior.catch(()=>{}).then(fn);locks.set(key(id),job);try{return await job;}finally{if(locks.get(key(id))===job)locks.delete(key(id));}}
 async function page(id){if(!valid(id))throw error('Некорректный ID задачи');const p=await notion('/pages/'+id,{method:'GET'});if(p.archived||p.in_trash)throw error('Задача удалена',409);const parent=p.parent||{};let source=sources().find(s=>(s.ds&&key(s.ds)===key(parent.data_source_id))||(s.db&&key(s.db)===key(parent.database_id)));if(!source&&parent.data_source_id&&sources().some(s=>s.db)){const schema=await notion('/data_sources/'+parent.data_source_id,{method:'GET'});source=sources().find(s=>s.db&&key(s.db)===key(schema.parent?.database_id));}if(!source)return {page:p,supported:false};return {page:p,source,supported:true};}
 function state(p){const fields={};for(const name of FIELDS){const property=p.properties?.[name];if(property&&property.type!=='files')throw error('Поле '+name+' должно иметь тип «Файлы и медиа»',409);const files=property?.files||[];fields[name]={available:!!property,version:version(files),images:files.map((f,index)=>({index,name:f.name||'Фото',url:safe(f.file?.url||f.external?.url),expiryTime:f.file?.expiry_time||''})).filter(f=>f.url)};}return fields;}
 async function load(id,{force=false}={}){if(!valid(id))throw error('Некорректный ID задачи');const k=key(id),cached=metadata.get(k);if(!force&&cached&&Date.now()-cached.at<20000)return structuredClone(cached.value);if(!force&&flights.has(k))return structuredClone(await flights.get(k));const job=(async()=>{const x=await page(id);const value={ok:true,supported:x.supported,fields:x.supported?state(x.page):{}};metadata.delete(k);metadata.set(k,{at:Date.now(),value});while(metadata.size>100)metadata.delete(metadata.keys().next().value);return value;})();if(!force)flights.set(k,job);try{return structuredClone(await job);}finally{if(flights.get(k)===job)flights.delete(k);}}

 async function schema(body){if(body.__account&&body.__account.role!=='admin')throw error('Только администратор может добавлять поля базы',403);const x=await page(body.id);if(!x.supported)throw error('Поля доступны только для Todo и Gorulen isler');const fields=state(x.page),properties={};for(const name of FIELDS)if(!fields[name].available)properties[name]={files:{}};if(Object.keys(properties).length){const ds=x.page.parent.data_source_id;if(ds)await notion('/data_sources/'+ds,{method:'PATCH',body:JSON.stringify({properties})});else await notion('/databases/'+x.source.db,{method:'PATCH',body:JSON.stringify({properties})},'2022-06-28');}metadata.delete(key(body.id));return load(body.id,{force:true});}
 async function change(body,ensureUpload){if(!FIELDS.includes(body.field))throw error('Неизвестное поле фотографии');return locked(body.id,async()=>{const pending=flights.get(key(body.id));if(pending)await pending.catch(()=>{});metadata.delete(key(body.id));const x=await page(body.id);if(!x.supported)throw error('Поля доступны только для Todo и Gorulen isler');const f=state(x.page)[body.field];if(!f.available)throw error('Добавьте поля Foto evvel и Foto sonra типа «Файлы и медиа» в Notion или нажмите «Создать поля» под администратором',409);const existing=x.page.properties[body.field].files||[];let files=existing.map(file=>({name:file.name,type:file.type,[file.type]:{url:file[file.type]?.url}}));if(body.remove){if(body.version!==f.version)throw error('Список фотографий изменился. Обновите его перед удалением.',409);if(!Number.isInteger(body.index)||body.index<0||body.index>=files.length)throw error('Фото уже удалено',409);files.splice(body.index,1);}else{if(files.length>=20)throw error('В одном поле можно хранить до 20 фотографий');const id=await ensureUpload(body.fileUploadId);const name='ADIB-'+id;if(!files.some(f=>f.name===name))files.push({name,type:'file_upload',file_upload:{id}});}
 try{await notion('/pages/'+body.id,{method:'PATCH',body:JSON.stringify({properties:{[body.field]:{files}}})});}catch(e){e.message+=' · Сохранение могло выполниться. Обновите фото перед повторной попыткой.';throw e;}metadata.delete(key(body.id));return load(body.id,{force:true});});}
 return {load,schema,change};
}
module.exports={create,FIELDS,version};
