/* Shared view chrome. Move real controls; keep their existing actions and state. */
(function(root){'use strict';
const make=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e};
const set=(node,text)=>{if(node&&node.textContent!==text)node.textContent=text};
const addClass=(node,name)=>{if(node&&!node.classList.contains(name))node.classList.add(name)};
function context(){const matrix=document.querySelector('.personal-eisenhower-modal');if(matrix)return ['Матрица Эйзенхауэра','Мои задачи · срочность и важность'];const board=document.querySelector('.personal-kanban-modal');if(board){const subject=board.__personalKanbanArgs?.title||'Мои задачи',list=board.querySelector('.personal-kanban-list-mode');return [(list?'Список':'Канбан')+' · '+subject,'Мои задачи · '+(list?'список задач':'задачи по группам')]}const equipmentBoard=document.querySelector('#taskModal.open.kanban-modal');if(equipmentBoard)return [document.getElementById('modalTitle')?.textContent?.trim()||'Канбан оборудования','Оборудование · задачи'];const personal=document.getElementById('personalMode');if(personal&&!personal.hidden){const scope=personal.querySelector('.personal-desktop-scope-title')?.textContent?.trim();return [scope?'Контейнер · '+scope:'Контейнеры','Мои задачи · контейнеры и задачи']}const current=document.querySelector('#crumbs .crumb.current')?.textContent?.trim();return [current&&current!=='ADIB'?'Оборудование · '+current:'Оборудование','Планы, зоны и объекты']}
let measured=null;const resize=new ResizeObserver(entries=>{for(const {target}of entries){if(target.id!=='adibWorkspaceHeader')continue;const h=Math.ceil(target.getBoundingClientRect().height),v=h+'px';if(document.documentElement.style.getPropertyValue('--adib-workspace-head-height')!==v)document.documentElement.style.setProperty('--adib-workspace-head-height',v)}});
function compact(){const head=document.getElementById('adibWorkspaceHeader');if(!head)return;if(measured!==head){resize.observe(head);measured=head}addClass(head,'adib-view-header');let group=head.querySelector('.adib-standard-heading');if(!group){group=make('div','adib-standard-heading');group.append(make('h1','adib-standard-title'),make('small','adib-standard-subtitle'));head.prepend(group)}const [title,sub]=context();set(group.firstElementChild,title);set(group.lastElementChild,sub);if(head.getAttribute('aria-label')!==title)head.setAttribute('aria-label',title);const actions=head.querySelector('.miro-mobile-actions');if(!actions)return;addClass(actions,'adib-standard-actions');const labels={miroMobileSearch:'Поиск',miroMobileList:'Вид',miroMobileFilter:'Фильтр',miroMobileChat:'Обсуждения',miroMobileAdd:'+ Задача'};for(const [id,label]of Object.entries(labels)){const b=document.getElementById(id);if(!b)continue;let text=b.querySelector('.adib-header-action-label');if(!text){text=make('span','adib-header-action-label');b.append(text)}set(text,label);if(id==='miroMobileAdd')addClass(b,'adib-header-primary')}const refresh=document.getElementById('miroMobileRefresh');if(refresh)addClass(refresh,'adib-header-refresh');}
function common(){for(const selector of ['.adib-home-top','.tm-head','.adib-calendar-bar','.adib-discussion-title'])document.querySelectorAll(selector).forEach(h=>addClass(h,'adib-view-header'));const calendar=document.querySelector('.adib-calendar-bar');if(calendar&&!calendar.querySelector('.adib-calendar-heading')){const group=make('div','adib-standard-heading adib-calendar-heading');group.append(make('h1','adib-standard-title','Календарь'));const month=calendar.querySelector('h2');if(month){month.classList.add('adib-standard-subtitle');group.append(month)}const controls=make('div','adib-standard-actions');for(const n of [...calendar.children])if(n!==month)controls.append(n);calendar.replaceChildren(group,controls)}const day=document.querySelector('.tm-head');if(day)addClass(day.querySelector('h2'),'adib-standard-title');const chat=document.querySelector('.adib-discussion-title');if(chat){addClass(chat.querySelector('h2'),'adib-standard-title');addClass(chat.querySelector('small'),'adib-standard-subtitle')}}
let scheduled=false;function update(){scheduled=false;compact();common()}const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(update)});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','class']});root.addEventListener('adib-home-data',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update)}});update();root.ADIBWorkspaceHeaders={refresh:update,context};
})(window);
